// Generated by `libxr gen`; do not edit by hand.
// Generated from mspm0_variants.syscfg (MSPM0G3507); SysConfig configures the
// clocks, pins, DMA channels and peripherals (SYSCFG_DL_init() in main.c). Put
// application code between the "User Code Begin" and "User Code End" markers.
#include "app_main.h"

#include "libxr.hpp"
#include "mspm0_gpio.hpp"
#include "mspm0_i2c.hpp"
#include "mspm0_pwm.hpp"
#include "mspm0_spi.hpp"
#include "mspm0_timebase.hpp"
#include "mspm0_uart.hpp"
#include "ti_msp_dl_config.h"
#include "xrobot_main.hpp"

using namespace LibXR;

/* User Code Begin 1 */
/* User Code End 1 */

// Input clocks: the BUSCLK of the power domain. PD0 from ULPCLK = CPUCLK_FREQ (no
// ULPCLK divider). The I2C driver resets the clock configuration of its peripherals, so
// the BUSCLK of the domain is the right argument.
static constexpr uint32_t PD0_BUSCLK_FREQ = CPUCLK_FREQ;
static constexpr uint32_t MFCLK_FREQ = 4000000;
// SPI_1 runs from MFCLK (4 MHz) divided by 4, as SysConfig configured it; the SPI
// driver keeps that clock configuration.
static constexpr uint32_t SPI_1_CLK_FREQ = MFCLK_FREQ / 4;

// Ownership of the DMA channels that serve a UART; MSPM0_UART_MAIN_INIT and
// MSPM0_UART_EXTEND_INIT check these names against the ones SysConfig generated.
#define DMA_CH_UART0_TX_LIBXR_UART_IRQN UART_0_INST_INT_IRQN
#define DMA_CH_UART0_TX_LIBXR_UART_TX 1
#define DMA_CH_UART0_RX_LIBXR_UART_IRQN UART_0_INST_INT_IRQN
#define DMA_CH_UART0_RX_LIBXR_UART_RX 1
#define DMA_CH_UART0_RX_LIBXR_FULL_CHANNEL 1
#define DMA_CH_UART0_RX_LIBXR_HALF_INTERRUPT 1
#define UART_0_LIBXR_EXTEND_CAPABLE 1

// DMA buffers. A UART gets 2 x N bytes for its two transmit halves; a UART Extend with
// DMA RX also gets its receive ring. The SPI DMA buffers are split in two halves as
// well; the I2C driver uses polling, its buffer is the staging area for DMA transfers.
alignas(size_t) static uint8_t uart0_tx_buf[2 * 128];
alignas(4) static uint8_t uart0_rx_dma_buf[128];
alignas(4) static uint8_t spi1_rx_buf[32];
alignas(4) static uint8_t spi1_tx_buf[32];
alignas(4) static uint8_t i2c0_buf[32];

extern "C" void app_main(void)
{
  /* User Code Begin 2 */
  /* User Code End 2 */

  // Timebase and platform
  static MSPM0Timebase timebase;
  PlatformInit();

  // GPIO: SysConfig configured USER_LED_1 (PA26), USER_LED_2 (PA27) as output pins and
  // gpio_btn_pin_0 (PA7) as input pins. The interrupt edge comes from SysConfig;
  // RegisterCallback and EnableInterrupt belong to the consumer (a Module or the User
  // Code).
  static MSPM0GPIO USER_LED_1(GPIO_LEDS_PORT, GPIO_LEDS_USER_LED_1_PIN,
                              GPIO_LEDS_USER_LED_1_IOMUX);
  static MSPM0GPIO USER_LED_2(GPIO_LEDS_PORT, GPIO_LEDS_USER_LED_2_PIN,
                              GPIO_LEDS_USER_LED_2_IOMUX);
  static MSPM0GPIO gpio_btn_pin_0(GPIO_BTN_PORT, GPIO_BTN_PIN_0_PIN,
                                  GPIO_BTN_PIN_0_IOMUX);

  // UART: TX with DMA; a UART Extend with DMA RX receives by circular DMA, the others on
  // byte interrupts.
  static MSPM0UART uart0(MSPM0_UART_EXTEND_INIT(UART_0, DMA_CH_UART0_TX, DMA_CH_UART0_RX,
                         uart0_tx_buf, sizeof(uart0_tx_buf), 5, uart0_rx_dma_buf,
                         sizeof(uart0_rx_dma_buf), 128));

  // I2C: polling; the buffer stages DMA transfers.
  static MSPM0I2C i2c0(MSPM0_I2C_INIT(I2C_0, PD0_BUSCLK_FREQ, i2c0_buf, sizeof(i2c0_buf),
                       8), {I2C_0_BUS_SPEED_HZ});

  // SPI: DMA for transfers longer than the threshold.
  static MSPM0SPI spi1(MSPM0_SPI_INIT(SPI_1, SPI_1_CLK_FREQ, DMA_CH_SPI1_RX,
                       DMA_CH_SPI1_TX, spi1_rx_buf, sizeof(spi1_rx_buf), spi1_tx_buf,
                       sizeof(spi1_tx_buf), 3));

  // PWM: the channels of one timer share one period, which SysConfig configures.
  static MSPM0PWM pwm_timg0_c0(MSPM0_PWM_CH(PWM_0, 0));
  static MSPM0PWM pwm_timg0_c1(MSPM0_PWM_CH(PWM_0, 1));

  // Terminal on uart0
  STDIO::read_ = uart0.read_port_;
  STDIO::write_ = uart0.write_port_;
  static RamFS ramfs("XRobot");
  static Terminal<32, 32, 5, 5> terminal(ramfs);
  static auto terminal_task = Timer::CreateTask(terminal.TaskFun, &terminal, 10);
  Timer::Add(terminal_task);
  Timer::Start(terminal_task);

  // Hardware registration
  XR_REGISTER(USER_LED_1, LibXR::GPIO);
  XR_REGISTER(USER_LED_2, LibXR::GPIO);
  XR_REGISTER(gpio_btn_pin_0, LibXR::GPIO);

  XR_REGISTER(pwm_timg0_c0, LibXR::PWM);
  XR_REGISTER(pwm_timg0_c1, LibXR::PWM);

  XR_REGISTER(spi1, LibXR::SPI);

  XR_REGISTER(uart0, LibXR::UART);

  XR_REGISTER(i2c0, LibXR::I2C);

  XR_REGISTER(ramfs, LibXR::RamFS);

  XR_REGISTER(terminal, LibXR::Terminal<32, 32, 5, 5>);

  /* User Code Begin 3 */
  /* User Code End 3 */
  XROBOT_MAIN();
}
