[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "libxr"
version = "5.2.4"
description = "C++ code generator for LibXR-based embedded systems, supporting STM32 and modular robotics applications."
requires-python = ">=3.8"
authors = [
    {name = "Xiao", email = "2592509183@qq.com"}
]
maintainers = [
    {name = "Xiao", email = "2592509183@qq.com"}
]
readme = "README.md"
license = {text = "Apache-2.0"}
keywords = ["code generation", "embedded systems", "automation"]
dependencies = [
    "pyyaml",
    "requests",
    "packaging"
]

[project.urls]
Homepage = "https://github.com/Jiu-xiao/libxr"
Documentation = "https://xrobot.work/"
Repository = "https://github.com/Jiu-xiao/LibXR_CppCodeGenerator"
"Bug Tracker" = "https://github.com/Jiu-xiao/LibXR_CppCodeGenerator/issues"

[project.scripts]
xr_parse_ioc = "libxr.PeripheralAnalyzerSTM32:main"
xr_parse = "libxr.PeripheralAnalyzer:main"
xr_gen_code_stm32 = "libxr.GeneratorCodeSTM32:main"
xr_gen_code = "libxr.GeneratorCode:main"
xr_stm32_cmake = "libxr.GeneratorSTM32CMake:main"
xr_stm32_flash = "libxr.STM32FlashGenerator:main"
xr_stm32_toolchain_switch = "libxr.STM32ToolchainSwitch:main"
xr_cubemx_cfg = "libxr.ConfigCubemxProject:main"
xr_cubemx_generate = "libxr.CubeMXGenerator:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"libxr" = ["libxr_version.py", "STM32FlashLayoutRules.xml"]
