"""libxr 命令（libxr.cli）：平台识别和各子命令共有的选项。
The libxr command (libxr.cli): platform recognition and the options the subcommands share.
"""

import contextlib
import io
import logging
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from fixtures import IOC, TestCase, run_libxr

from libxr import cli, update_notice

REPOSITORY = Path(__file__).resolve().parents[1]


class Platforms(TestCase):
    """parse 按工程目录识别平台并记录在 YAML 中，gen 按记录的平台选择生成器；无法识别时报错并
    列出支持的平台。
    parse recognizes the platform by the project directory and records it in the YAML, and gen
    selects the generator by the recorded platform; when none matches, they fail with the
    supported platforms.
    """

    def setUp(self):
        super().setUp()
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)

    def test_an_unrecognized_project_is_an_error(self):
        with self.assertLogs(level="ERROR") as logs:
            code, _, _ = run_libxr("parse", "-d", str(self.root))
        self.assertEqual(code, 1)
        self.assertEqual(
            logs.output,
            [
                f"ERROR:root:{self.root}: no supported platform recognized "
                "(stm32: a directory with an STM32CubeMX .ioc file)"
            ],
        )

    def parsed_elsewhere(self):
        """解析 root/project 中的工程，把配置 YAML 写到工程之外，当前目录也移到工程之外；返回
        工程目录和 YAML 路径。
        Parse the project in root/project into a configuration YAML outside the project and
        move the current directory outside it too; return the project directory and the YAML.
        """
        project = self.root / "project"
        project.mkdir()
        (project / "demo.ioc").write_text(IOC, encoding="utf-8")
        config = self.root / "elsewhere" / "cubemx.yaml"
        config.parent.mkdir()
        self.assertEqual(run_libxr("parse", "-d", str(project), "-o", str(config))[0], 0)
        previous = Path.cwd()
        os.chdir(self.root)
        self.addCleanup(os.chdir, previous)
        return project, config

    def test_gen_takes_the_platform_that_parse_recorded(self):
        project, config = self.parsed_elsewhere()
        self.assertEqual(config.read_text(encoding="utf-8").splitlines()[1], "Platform: stm32")
        output = project / "User" / "app_main.cpp"
        self.assertEqual(run_libxr("gen", "-i", str(config), "-o", str(output))[0], 0)
        self.assertTrue(output.is_file())

    def test_the_generated_files_name_the_ioc_file_and_the_settings(self):
        project, config = self.parsed_elsewhere()
        self.assertEqual(config.read_text(encoding="utf-8").splitlines()[2], "Ioc: demo.ioc")
        output = project / "User" / "app_main.cpp"
        self.assertEqual(run_libxr("gen", "-i", str(config), "-o", str(output))[0], 0)
        self.assertEqual(
            output.read_text(encoding="utf-8").splitlines()[0],
            "// Generated by `libxr gen` from demo.ioc and User/libxr_config.yaml.",
        )

    def test_without_a_recorded_platform_gen_reads_the_project_directory(self):
        # 旧版 parse 写出的 YAML 没有 Platform；默认的工程目录是当前目录，这里不是工程。
        # A YAML written by an older parse has no Platform; the default project directory is
        # the current one, which is not a project here.
        project, config = self.parsed_elsewhere()
        text = config.read_text(encoding="utf-8").replace("Platform: stm32\n", "")
        config.write_text(text, encoding="utf-8")
        output = project / "User" / "app_main.cpp"
        argv = ["gen", "-i", str(config), "-o", str(output)]
        with self.assertLogs(level="ERROR") as logs:
            self.assertEqual(run_libxr(*argv)[0], 1)
        self.assertEqual(
            logs.output,
            [
                "ERROR:root:.: no supported platform recognized "
                "(stm32: a directory with an STM32CubeMX .ioc file)"
            ],
        )
        self.assertFalse(output.exists())
        self.assertEqual(run_libxr(*argv, "-d", str(project))[0], 0)
        self.assertTrue(output.is_file())

    def test_an_unsupported_recorded_platform_is_an_error(self):
        config = self.root / "cubemx.yaml"
        config.write_text("Platform: zephyr\n", encoding="utf-8")
        with self.assertLogs(level="ERROR") as logs:
            self.assertEqual(run_libxr("gen", "-i", str(config), "-o", "app_main.cpp")[0], 1)
        self.assertEqual(
            logs.output,
            [
                f"ERROR:root:{config}: platform 'zephyr' is not supported "
                "(stm32: a directory with an STM32CubeMX .ioc file)"
            ],
        )

    def test_a_missing_directory_is_an_error(self):
        config = self.root / "cubemx.yaml"
        config.write_text("Mcu: {}\n", encoding="utf-8")
        for argv in (
            ["parse", "-d", "absent"],
            ["gen", "-i", str(config), "-o", "y.cpp", "-d", "absent"],
        ):
            with self.subTest(command=argv[0]), self.assertLogs(level="ERROR") as logs:
                self.assertEqual(run_libxr(*argv)[0], 1)
            self.assertEqual(logs.output, ["ERROR:root:Directory does not exist: absent"])


class Options(TestCase):
    """所有子命令共有的 --verbose，以及 gen 对 XRobot 的选择。
    The --verbose that every subcommand has, and the XRobot choice of gen.
    """

    def setUp(self):
        super().setUp()
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        root = logging.getLogger()
        self.addCleanup(root.setLevel, root.level)

    def test_python_m_libxr_is_the_libxr_command(self):
        # 以前只有 CI 的 import smoke 脚本碰过 __main__，而且是把它当模块导入。
        # Only the CI import smoke script used to touch __main__, importing it as a module.
        result = subprocess.run(
            [sys.executable, "-m", "libxr", "--version"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            env=dict(os.environ, XR_LANG="en"),
            check=False,
        )
        # 从源码目录运行（只设 PYTHONPATH）时没有安装信息，版本显示为 unknown。
        # Run from a source tree, with only PYTHONPATH set, there is no installation record
        # and the version shows as unknown.
        self.assertEqual(
            (result.returncode, result.stdout),
            (0, f"libxr {update_notice.installed_version() or 'unknown'}\n"),
        )

    def parsed(self, *argv):
        """解析 argv，返回参数字典；run 换成处理函数的名字。
        Parse argv and return the arguments as a dict, with run replaced by the handler's name.
        """
        arguments = vars(cli.build_parser().parse_args(argv))
        arguments["run"] = arguments["run"].__name__
        return arguments

    def test_every_option_reaches_its_argument(self):
        # 每个子命令一条只给必需参数的命令行（得到默认值）和一条给出全部选项的命令行。
        # Per subcommand, one command line with only the required arguments, giving the
        # defaults, and one with every option.
        quiet = {"verbose": False}
        loud = {"verbose": True}
        setup = {"terminal": "", "commit": "", "git_source": "auto", "git_mirrors": ""}
        toolchain = {"run": "cmd_stm32_toolchain"}
        pins = {"run": "cmd_pins"}
        pins_default = {"package": None, "format": "yaml", "directory": None, "libxr_config": None}
        for argv, expected in (
            (["parse"], {"directory": ".", "output": None, **quiet, "run": "cmd_parse"}),
            (
                ["parse", "-d", "p", "-o", "o.yaml", "--verbose"],
                {"directory": "p", "output": "o.yaml", **loud, "run": "cmd_parse"},
            ),
            (
                ["gen", "-i", "x", "-o", "y"],
                {
                    "input": "x",
                    "directory": ".",
                    "output": "y",
                    "xrobot": None,
                    "libxr_config": "",
                    **quiet,
                    "run": "cmd_gen",
                },
            ),
            (
                ["gen", "--input", "x", "--output", "y", "--directory", "p", "--xrobot"]
                + ["--libxr-config", "c.yaml", "--verbose"],
                {
                    "input": "x",
                    "directory": "p",
                    "output": "y",
                    "xrobot": True,
                    "libxr_config": "c.yaml",
                    **loud,
                    "run": "cmd_gen",
                },
            ),
            (
                ["stm32", "setup", "--xrobot"],
                {"directory": ".", "xrobot": True, **setup, **quiet, "run": "cmd_stm32_setup"},
            ),
            (
                ["stm32", "setup", "-d", "p", "-t", "usart1", "--no-xrobot", "--commit", "abc"]
                + ["--git-source", "github", "--git-mirrors", "m1,m2", "--verbose"],
                {
                    "directory": "p",
                    "terminal": "usart1",
                    "xrobot": False,
                    "commit": "abc",
                    "git_source": "github",
                    "git_mirrors": "m1,m2",
                    **loud,
                    "run": "cmd_stm32_setup",
                },
            ),
            (
                ["stm32", "cubemx-gen"],
                {
                    "directory": ".",
                    "ioc": "",
                    "cubemx_cmd": "",
                    "java_cmd": "",
                    "launch_mode": "auto",
                    "generate_code_dir": "",
                    "expect_path": None,
                    "log_dir": "",
                    "script_path": "",
                    "keep_script": False,
                    "silent": False,
                    "firmware": None,
                    "download": False,
                    "timeout": 1200,
                    **quiet,
                    "run": "cmd_stm32_cubemx_gen",
                },
            ),
            (
                ["stm32", "cubemx-gen", "-d", "p", "--ioc", "a.ioc", "--cubemx-cmd", "c"]
                + ["--java-cmd", "j", "--launch-mode", "java", "--generate-code-dir", "g"]
                + ["--expect-path", "a", "--expect-path", "b", "--log-dir", "l"]
                + ["--script-path", "s", "--keep-script", "--silent", "--firmware", "migrate"]
                + ["--download", "--timeout", "60", "--verbose"],
                {
                    "directory": "p",
                    "ioc": "a.ioc",
                    "cubemx_cmd": "c",
                    "java_cmd": "j",
                    "launch_mode": "java",
                    "generate_code_dir": "g",
                    "expect_path": ["a", "b"],
                    "log_dir": "l",
                    "script_path": "s",
                    "keep_script": True,
                    "silent": True,
                    "firmware": "migrate",
                    "download": True,
                    "timeout": 60,
                    **loud,
                    "run": "cmd_stm32_cubemx_gen",
                },
            ),
            (["stm32", "cmake"], {"directory": ".", **quiet, "run": "cmd_stm32_cmake"}),
            (
                ["stm32", "cmake", "-d", "p", "--verbose"],
                {"directory": "p", **loud, "run": "cmd_stm32_cmake"},
            ),
            (
                ["stm32", "flash-info", "STM32F103C8T6", "--verbose"],
                {"model": "STM32F103C8T6", **loud, "run": "cmd_stm32_flash_info"},
            ),
            (
                ["pins", "STM32H723VGT6"],
                {**pins_default, "model": "STM32H723VGT6", **quiet, **pins},
            ),
            (
                ["pins", "MSPM0G3507", "-p", "PM", "-f", "json", "--verbose"],
                {
                    **pins_default,
                    "model": "MSPM0G3507",
                    "package": "PM",
                    "format": "json",
                    **loud,
                    **pins,
                },
            ),
            (
                ["pins", "-d", "p", "-c", "c.yaml"],
                {
                    **pins_default,
                    "model": None,
                    "directory": "p",
                    "libxr_config": "c.yaml",
                    **quiet,
                    **pins,
                },
            ),
            (
                ["stm32", "toolchain", "gcc"],
                {"directory": ".", "compiler": "gcc", "std": None, **quiet, **toolchain},
            ),
            (
                ["stm32", "toolchain", "clang", "-d", "p", "-n", "--verbose"],
                {"directory": "p", "compiler": "clang", "std": "newlib", **loud, **toolchain},
            ),
            (
                ["stm32", "toolchain", "clang", "--hybrid"],
                {"directory": ".", "compiler": "clang", "std": "hybrid", **quiet, **toolchain},
            ),
            (
                ["stm32", "toolchain", "clang", "-p"],
                {"directory": ".", "compiler": "clang", "std": "picolibc", **quiet, **toolchain},
            ),
        ):
            with self.subTest(argv=argv):
                self.assertEqual(self.parsed(*argv), expected)

    def test_a_missing_required_argument_is_named(self):
        for argv, message in (
            (
                ["gen", "-o", "y"],
                "libxr gen: error: the following arguments are required: -i/--input",
            ),
            (
                ["gen", "-i", "x"],
                "libxr gen: error: the following arguments are required: -o/--output",
            ),
            (
                ["stm32", "flash-info"],
                "libxr stm32 flash-info: error: the following arguments are required: model",
            ),
            (
                ["stm32", "toolchain"],
                "libxr stm32 toolchain: error: the following arguments are required: compiler",
            ),
        ):
            with (
                self.subTest(argv=argv),
                contextlib.redirect_stderr(io.StringIO()) as error,
                self.assertRaises(SystemExit) as exit,
            ):
                cli.build_parser().parse_args(argv)
            self.assertEqual((exit.exception.code, error.getvalue().splitlines()[-1]), (2, message))

    def test_a_cubemx_gen_failure_logs_the_traceback_under_verbose(self):
        with (
            mock.patch(
                "libxr.cubemx_generator.generate_cubemx_project",
                side_effect=RuntimeError("broken"),
            ),
            self.assertLogs(level="DEBUG") as logs,
        ):
            self.assertEqual(run_libxr("stm32", "cubemx-gen", "--verbose")[0], 1)
        self.assertEqual(logs.output[0], "ERROR:root:broken")
        self.assertTrue(logs.output[1].startswith("DEBUG:root:Traceback:\nTraceback"))

    def gen_xrobot(self, *options, existing=None):
        """以 options 运行 gen，返回传给生成器的 use_xrobot；existing 为已有输出文件的内容。
        Run gen with options and return the use_xrobot passed to the generator; existing is
        the content of an existing output file.
        """
        config = self.root / "cubemx.yaml"
        config.write_text("Platform: stm32\n", encoding="utf-8")
        output = self.root / "app_main.cpp"
        if existing is not None:
            output.write_text(existing, encoding="utf-8")
        with mock.patch("libxr.generator_code_stm32.generate") as generate:
            argv = ["gen", "-i", str(config), "-o", str(output), *options]
            self.assertEqual(run_libxr(*argv)[0], 0)
        return generate.call_args.args[2]

    def test_gen_keeps_the_xrobot_choice_of_the_output_file(self):
        xrobot = '#include "xrobot_main.hpp"\n'
        self.assertIs(self.gen_xrobot(), False)
        self.assertIs(self.gen_xrobot(existing="int x;\n"), False)
        with self.assertLogs(level="INFO") as logs:
            self.assertIs(self.gen_xrobot(existing=xrobot), True)
        self.assertEqual(
            logs.output,
            [
                f"INFO:root:{self.root / 'app_main.cpp'} uses XRobot; generating with --xrobot "
                "(--no-xrobot turns it off)."
            ],
        )
        self.assertIs(self.gen_xrobot("--no-xrobot", existing=xrobot), False)
        self.assertIs(self.gen_xrobot("--xrobot", existing="int x;\n"), True)


if __name__ == "__main__":
    unittest.main()
