"""libxr parse 的 STM32 解析器（libxr.peripheral_analyzer_stm32）：输出位置、生成说明和读出的
外设配置。
The STM32 parser of libxr parse (libxr.peripheral_analyzer_stm32): where its YAML goes, the
notice at its top, and the peripheral configuration it reads.
"""

import contextlib
import io
import tempfile
import textwrap
import unittest
from pathlib import Path
from unittest import mock

from fixtures import IOC, MULTICORE_IOC, TestCase, run_libxr

from libxr import peripheral_analyzer_stm32

NOTICE = "# Generated by `libxr parse` from the CubeMX .ioc file; do not edit by hand."

# STM32CubeH5 例程 UART_TwoBoards_ComDMA（STM32H503）的 .ioc 片段：USART1 的发送和接收各用
# 一个 GPDMA1 通道，另有一个启用的 IWDG。
# An .ioc excerpt of the STM32CubeH5 example UART_TwoBoards_ComDMA (STM32H503): USART1 sends
# and receives through one GPDMA1 channel each, plus an enabled IWDG.
H5_IOC = textwrap.dedent("""\
    Mcu.Family=STM32H5
    Mcu.Name=STM32H503RBTx
    Mcu.UserName=STM32H503RBTx
    Mcu.CPN=STM32H503RBT6
    Mcu.IP0=GPDMA1
    Mcu.IP1=IWDG
    Mcu.IP2=USART1
    Mcu.IPNb=3
    GPDMA1.DIRECTION_GPDMACH0=DMA_MEMORY_TO_PERIPH
    GPDMA1.REQUEST_GPDMACH0=GPDMA1_REQUEST_USART1_TX
    GPDMA1.REQUEST_GPDMACH1=GPDMA1_REQUEST_USART1_RX
    IWDG.Prescaler=IWDG_PRESCALER_64
    IWDG.Reload=4095
    PA1.Signal=USART1_RX
    PB14.Signal=USART1_TX
    USART1.BaudRate=9600
    USART1.IPParameters=BaudRate,VirtualMode
    USART1.VirtualMode=VM_ASYNC
    VP_IWDG_VS_IWDG.Mode=IWDG_Activate
    """)

# STM32CubeH5 例程 USART_SlaveMode_DMA 的片段：USART1 为同步从机，CubeMX 生成的句柄是
# USART_HandleTypeDef husart1。
# An excerpt of the STM32CubeH5 example USART_SlaveMode_DMA: USART1 is a synchronous slave and
# the handle CubeMX generates is USART_HandleTypeDef husart1.
SYNC_USART_IOC = textwrap.dedent(r"""
    Mcu.Family=STM32H5
    Mcu.CPN=STM32H503RBT6
    GPDMA1.REQUEST_GPDMACH0=GPDMA1_REQUEST_USART1_TX
    GPDMA1.REQUEST_GPDMACH1=GPDMA1_REQUEST_USART1_RX
    PB12.Mode=Synchronous Slave
    PB12.Signal=USART1_CK
    PB14.Mode=Synchronous Slave
    PB14.Signal=USART1_TX
    PB15.Mode=Synchronous Slave
    PB15.Signal=USART1_RX
    USART1.BaudRate=9600
    USART1.VirtualMode=VM_SYNC
    USART1.VirtualMode-Synchronous\ Slave=VM_SYNC
    """)

# STM32CubeH5 例程 SMBUS_TwoBoards_ComIT_Master 的片段：I2C2 为 SMBus，CubeMX 生成的句柄是
# SMBUS_HandleTypeDef hsmbus2。
# An excerpt of the STM32CubeH5 example SMBUS_TwoBoards_ComIT_Master: I2C2 runs SMBus and the
# handle CubeMX generates is SMBUS_HandleTypeDef hsmbus2.
SMBUS_IOC = textwrap.dedent("""
    Mcu.Family=STM32H5
    Mcu.CPN=STM32H503RBT6
    I2C2.SMBusPeripheralMode=SMBUS_PERIPHERAL_MODE_SMBUS_HOST
    I2C2.Timing=0x608087CA
    Mcu.IP1=I2C2
    PB10.Mode=SMBus-two-wire-Interface
    PB10.Signal=I2C2_SCL
    PB13.Mode=SMBus-two-wire-Interface
    PB13.Signal=I2C2_SDA
    """)

# STM32CubeMX 6.18.1 保存的 DevC 副本中 ADC3 的片段：12 个 rank，第 12 个再次转换 IN8。key 按
# 文本排序，Channel-10 和 Channel-11 在 Channel-2 之前；CubeMX 生成的 MX_ADC3_Init 按 rank
# 依次配置 IN8、1、2、3、5、6、7、9、13、14、15、8。
# ADC3 of a DevC copy saved by STM32CubeMX 6.18.1: 12 ranks, the 12th converting IN8 again.
# The keys are sorted as text, Channel-10 and Channel-11 before Channel-2; MX_ADC3_Init
# generated by CubeMX configures IN8, 1, 2, 3, 5, 6, 7, 9, 13, 14, 15, 8 by rank.
ADC_RANKS_IOC = textwrap.dedent(r"""
    ADC3.Channel-0\#ChannelRegularConversion=ADC_CHANNEL_8
    ADC3.Channel-1\#ChannelRegularConversion=ADC_CHANNEL_1
    ADC3.Channel-10\#ChannelRegularConversion=ADC_CHANNEL_15
    ADC3.Channel-11\#ChannelRegularConversion=ADC_CHANNEL_8
    ADC3.Channel-2\#ChannelRegularConversion=ADC_CHANNEL_2
    ADC3.Channel-3\#ChannelRegularConversion=ADC_CHANNEL_3
    ADC3.Channel-4\#ChannelRegularConversion=ADC_CHANNEL_5
    ADC3.Channel-5\#ChannelRegularConversion=ADC_CHANNEL_6
    ADC3.Channel-6\#ChannelRegularConversion=ADC_CHANNEL_7
    ADC3.Channel-7\#ChannelRegularConversion=ADC_CHANNEL_9
    ADC3.Channel-8\#ChannelRegularConversion=ADC_CHANNEL_13
    ADC3.Channel-9\#ChannelRegularConversion=ADC_CHANNEL_14
    ADC3.ContinuousConvMode=ENABLE
    ADC3.DMAContinuousRequests=ENABLE
    ADC3.NbrOfConversion=12
    ADC3.Rank-0\#ChannelRegularConversion=1
    ADC3.Rank-1\#ChannelRegularConversion=2
    ADC3.Rank-10\#ChannelRegularConversion=11
    ADC3.Rank-11\#ChannelRegularConversion=12
    ADC3.ScanConvMode=ENABLE
    Dma.ADC3.9.Instance=DMA2_Stream1
    Dma.ADC3.9.Mode=DMA_CIRCULAR
    Dma.Request9=ADC3
    Mcu.CPN=STM32F407IGH6
    Mcu.Family=STM32F4
    """)


# 一个双核 .ioc 的最小片段：CortexM7 拥有 USART3，CortexM4 拥有 USART1。
# A minimal dual-core .ioc excerpt: CortexM7 owns USART3 and CortexM4 owns USART1.
DUAL_CORE_IOC = textwrap.dedent("""\
    Mcu.Context0=CortexM7
    Mcu.Context1=CortexM4
    Mcu.ContextNb=2
    Mcu.Family=STM32H7
    Mcu.Name=STM32H755BIT6
    Mcu.UserName=STM32H755BIT6
    CortexM7.IPs=RCC\\:I,NVIC1\\:I,USART3\\:I
    CortexM4.IPs=RCC\\:I,NVIC2\\:I,USART1\\:I
    USART1.BaudRate=115200
    USART3.BaudRate=115200
    """)


class ParseIoc(TestCase):
    """命令行：读取目录中唯一的 .ioc 文件并写出 YAML。
    The command line: read the one .ioc file of a directory and write the YAML.
    """

    def setUp(self):
        super().setUp()
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.project = Path(temporary.name)
        (self.project / "demo.ioc").write_text(IOC, encoding="utf-8")

    def parse(self, *argv):
        """以这些参数运行 libxr parse，返回退出码。
        Run libxr parse with these arguments and return the exit code.
        """
        return run_libxr("parse", "-d", str(self.project), *argv)[0]

    def test_the_default_output_is_config_yaml_in_the_directory(self):
        self.assertEqual(self.parse(), 0)
        output = self.project / ".config.yaml"
        self.assertEqual(output.read_text(encoding="utf-8").splitlines()[0], NOTICE)
        self.assertFalse((self.project / "demo.yaml").exists())

    def test_the_output_directory_is_created_and_written_without_anchors(self):
        output = self.project / ".ci-tools" / "cubemx.yaml"
        self.assertEqual(self.parse("-o", str(output)), 0)
        text = output.read_text(encoding="utf-8")
        # USART1 的 DMA 配置同时出现在外设和 DMA 段中，两处都完整写出。
        # The DMA configuration of USART1 is under the peripheral and in the DMA section, both
        # written in full.
        self.assertNotIn("&id", text)
        self.assertEqual(text.count("stream: DMA2_Stream5"), 2)

    def test_several_ioc_files_are_refused(self):
        (self.project / "other.ioc").write_text(IOC, encoding="utf-8")
        with self.assertLogs(level="ERROR") as logs:
            self.assertEqual(self.parse(), 1)
        self.assertEqual(
            logs.output,
            [
                f"ERROR:root:{self.project} holds several .ioc files (demo.ioc, other.ioc); run "
                "`libxr parse` on a directory with one CubeMX project"
            ],
        )
        self.assertFalse((self.project / ".config.yaml").exists())

    def test_an_unreadable_ioc_file_fails_the_command(self):
        (self.project / "demo.ioc").write_bytes(b"Mcu.Family=\xff\xfe\n")
        with self.assertLogs(level="ERROR") as logs:
            self.assertEqual(self.parse(), 1)
        self.assertEqual(
            logs.output,
            [
                f"ERROR:root:{self.project / 'demo.ioc'} is not UTF-8 text (byte 12); "
                "save it as UTF-8"
            ],
        )
        self.assertFalse((self.project / ".config.yaml").exists())

    def test_an_unknown_context_fails_the_command(self):
        (self.project / "demo.ioc").write_text(DUAL_CORE_IOC, encoding="utf-8")
        with self.assertLogs(level="ERROR") as logs:
            self.assertEqual(self.parse("--context", "CortexM33"), 1)
        self.assertEqual(
            logs.output,
            [
                f"ERROR:root:{self.project / 'demo.ioc'}: Unknown CubeMX context: CortexM33; "
                "a context names one core of a multicore project"
            ],
        )
        self.assertFalse((self.project / ".config.yaml").exists())

    def test_a_context_without_an_ip_list_fails_the_command(self):
        # 有 Mcu.Context0，却没有它的 IP 列表条目 CortexM4.IPs。
        # Mcu.Context0 is there, but its IP list entry CortexM4.IPs is not.
        (self.project / "demo.ioc").write_text(
            "Mcu.Context0=CortexM4\nMcu.ContextNb=1\n", encoding="utf-8"
        )
        with self.assertLogs(level="ERROR") as logs:
            self.assertEqual(self.parse("--context", "CortexM4"), 1)
        self.assertEqual(
            logs.output,
            [
                f"ERROR:root:{self.project / 'demo.ioc'}: CubeMX context CortexM4 has no IP "
                "list; the .ioc file is incomplete"
            ],
        )
        self.assertFalse((self.project / ".config.yaml").exists())

    def test_a_single_core_project_has_no_context_to_parse(self):
        # setUp 写入的 .ioc 是单核工程的，没有 Mcu.ContextN 条目。
        # The .ioc of setUp is a single-core project: it has no Mcu.ContextN entry.
        with self.assertLogs(level="ERROR") as logs:
            self.assertEqual(self.parse("--context", "CortexM7"), 1)
        self.assertEqual(
            logs.output,
            [
                f"ERROR:root:{self.project / 'demo.ioc'}: Unknown CubeMX context: CortexM7; "
                "a context names one core of a multicore project"
            ],
        )
        self.assertFalse((self.project / ".config.yaml").exists())

    def test_a_known_context_of_a_multicore_project_is_parsed(self):
        (self.project / "demo.ioc").write_text(DUAL_CORE_IOC, encoding="utf-8")
        self.assertEqual(self.parse("--context", "CortexM4"), 0)
        text = (self.project / ".config.yaml").read_text(encoding="utf-8")
        # 只解析 CortexM4 的硬件：有它的 USART1，没有 CortexM7 的 USART3。
        # Only the hardware of CortexM4 is parsed: its USART1 is there, the USART3 of
        # CortexM7 is not.
        self.assertIn("USART1", text)
        self.assertNotIn("USART3", text)


class MulticoreContextOwnership(TestCase):
    """多核 .ioc 的按核解析：共享外设归初始化它的核，时基和引脚归属按上下文分组。
    The per-core parsing of a multicore .ioc: a shared peripheral belongs to the core
    initializing it, and timebase and pin ownership follow the context groups.
    """

    def setUp(self):
        super().setUp()
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.project = Path(temporary.name)
        (self.project / "demo.ioc").write_text(MULTICORE_IOC, encoding="utf-8")

    def parse(self, context):
        """解析一个核的硬件，返回配置结构。
        Parse the hardware of one core and return the configuration structure.
        """
        return peripheral_analyzer_stm32.parse_ioc_file(str(self.project / "demo.ioc"), context)

    def test_a_shared_peripheral_belongs_to_the_core_initializing_it(self):
        # CM4 列出 USART3 不带 \:I：只作参考，不生成它，否则 CM4 的 app_main.cpp 里出现
        # CM4 的 main.c 从不定义的 huart3，链接失败，两个核还会驱动同一个串口。
        # CM4 lists USART3 without \:I: for reference only, so it is not generated; if
        # it were, CM4's app_main.cpp would reference huart3, which CM4's main.c never
        # defines, the link fails and both cores drive one UART.
        cm7 = self.parse("CortexM7")
        cm4 = self.parse("CortexM4")
        self.assertIn("USART3", cm7["Peripherals"]["USART"])
        self.assertNotIn("USART", cm4["Peripherals"])
        # 共享的 DMA 条目同样只归初始化的 CM7：CM4 的 DMA 段一条配置都不剩。
        # The shared DMA entries belong to the initializing CM7 only as well: CM4's
        # DMA section keeps not one configuration.
        self.assertTrue(cm7["DMA"])
        self.assertEqual(cm4["DMA"], {"Requests": {}, "Configurations": {}})

    def test_the_timebase_is_read_from_the_nvic_group_of_the_context(self):
        # 真实文件写 NVIC2.TimeBaseIP=TIM6（CM4 的 HAL 时基），NVIC1 没有时基条目；解析
        # 写 NVIC.TimeBase* 的代码两个核都退化成 SysTick。
        # Real files write NVIC2.TimeBaseIP=TIM6, the HAL timebase of CM4, and NVIC1
        # has no timebase entry; code that reads NVIC.TimeBase* only degrades both
        # cores to SysTick.
        self.assertEqual(
            self.parse("CortexM4")["Timebase"], {"Source": "TIM6", "IRQ": "TIM6_DAC_IRQn"}
        )
        self.assertEqual(self.parse("CortexM7")["Timebase"], {"Source": "SysTick", "IRQ": None})

    def test_free_pins_and_ports_after_k_are_kept_for_both_cores(self):
        # PinAttribute=Free 的板载 LED 和按钮以前两个核都丢掉；L 以后端口的引脚也一样。
        # The board LED and the button with PinAttribute=Free used to be dropped for
        # both cores, as were pins on ports after L.
        for context in ("CortexM7", "CortexM4"):
            with self.subTest(context=context):
                pins = self.parse(context)["GPIO"]
                self.assertIn("PC13", pins)
                self.assertEqual(pins["PC13"].get("Label"), "USER_BUTTON")
                self.assertIn("PL7", pins)
        cm7 = self.parse("CortexM7")["GPIO"]
        self.assertIn("PE1", cm7)
        self.assertIn("PL5", cm7)
        self.assertNotIn("PE1", self.parse("CortexM4")["GPIO"])

    def test_a_single_channel_timer_keeps_its_channel_mode_from_the_shared_entry(self):
        # SH.S_TIM16_CH1 被丢掉时，TIM16.Channel=CH1 找不到模式，回退把输入捕获通道记成
        # PWM 通道；模式条目在时，该定时器一个通道都不记。
        # When SH.S_TIM16_CH1 is dropped, TIM16.Channel=CH1 finds no mode and the
        # fallback records the input capture channel as a PWM channel; with the mode
        # entry the timer records no channel at all.
        tim16 = self.parse("CortexM7")["Peripherals"]["TIM"]["TIM16"]
        self.assertFalse(tim16.get("Channels"))

    def test_the_project_manager_entries_of_the_other_core_are_dropped(self):
        # functionlistsort 被丢掉时，CM7 的 TIM2 用 LL 驱动也照常生成，YAML 引用 CubeMX
        # 不生成的 HAL 句柄；TIM6 在 CM4 上取消了代码生成，同样要丢掉。
        # When functionlistsort is dropped, CM7's TIM2 is generated even on the LL
        # driver, so the YAML references a HAL handle CubeMX never generates; TIM6 has
        # generation off on CM4 and must be dropped there too.
        with self.assertLogs(level="WARNING") as logs:
            cm7 = self.parse("CortexM7")
        self.assertNotIn("TIM2", cm7["Peripherals"]["TIM"])
        self.assertTrue(any("LL driver" in message for message in logs.output), logs.output)
        cm4 = self.parse("CortexM4")
        self.assertNotIn("TIM6", cm4["Peripherals"].get("TIM", {}))
        self.assertEqual(cm7["Timebase"]["Source"], "SysTick")

    def test_the_nvic_group_of_a_context_is_kept_for_it(self):
        raw_map = peripheral_analyzer_stm32._extract_key_value_pairs(io.StringIO(MULTICORE_IOC))
        cm7 = peripheral_analyzer_stm32.filter_ioc_context(raw_map, "CortexM7")
        cm4 = peripheral_analyzer_stm32.filter_ioc_context(raw_map, "CortexM4")
        self.assertIn("NVIC1.SysTick_IRQn", cm7)
        self.assertNotIn("NVIC2.SysTick_IRQn", cm7)
        self.assertIn("NVIC2.SysTick_IRQn", cm4)
        self.assertNotIn("NVIC1.SysTick_IRQn", cm4)
        # 共享条目和 Project Manager 设置两个核都保留。
        # The shared entries and the Project Manager settings are kept for both cores.
        for kept in (cm7, cm4):
            self.assertIn("SH.GPXTI7.0", kept)
            self.assertIn("ProjectManager.functionlistsort", kept)
        # functionlistsort 只留本上下文的条目。
        # functionlistsort keeps this context's entries only.
        self.assertNotIn("MX_TIM6_Init", cm7["ProjectManager.functionlistsort"])
        self.assertIn("MX_TIM2_Init", cm7["ProjectManager.functionlistsort"])
        self.assertNotIn("MX_TIM2_Init", cm4["ProjectManager.functionlistsort"])
        self.assertIn("MX_TIM6_Init", cm4["ProjectManager.functionlistsort"])

    def test_ip_lists_without_init_markers_belong_to_every_context(self):
        # 不带任何 \:I 标记的文件（CubeMX 6 之前的写法）中，IP 列表里的条目都归该上下文。
        # In a file without any \:I marker, one written before CubeMX 6, every entry of
        # an IP list belongs to its context.
        raw_map = peripheral_analyzer_stm32._extract_key_value_pairs(
            io.StringIO(
                "Mcu.Context0=CortexM7\n"
                "Mcu.Context1=CortexM4\n"
                "Mcu.ContextNb=2\n"
                "CortexM7.IPs=RCC,USART3,SYS\n"
                "CortexM4.IPs=RCC,USART1,SYS_M4\n"
                "USART3.BaudRate=115200\n"
                "USART1.BaudRate=115200\n"
            )
        )
        cm7 = peripheral_analyzer_stm32._context_ip_names(raw_map, "CortexM7")
        cm4 = peripheral_analyzer_stm32._context_ip_names(raw_map, "CortexM4")
        self.assertIn("USART3", cm7)
        self.assertIn("RCC", cm4)
        self.assertIn("USART1", cm4)
        # 归属仍按各自的列表：CM4 拿到自己的 USART1，不拿 CM7 列表里的 USART3。
        # Ownership still follows each list: CM4 gets its own USART1 and not the
        # USART3 that only the CM7 list holds.
        kept = peripheral_analyzer_stm32.filter_ioc_context(raw_map, "CortexM4")
        self.assertIn("USART1.BaudRate", kept)
        self.assertNotIn("USART3.BaudRate", kept)
        kept = peripheral_analyzer_stm32.filter_ioc_context(raw_map, "CortexM7")
        self.assertIn("USART3.BaudRate", kept)
        self.assertNotIn("USART1.BaudRate", kept)


class ParsedConfiguration(TestCase):
    """从 .ioc 条目读出的外设和 RTOS 配置。
    The peripheral and RTOS configuration read from .ioc entries.
    """

    def parse(self, extra, ioc=IOC):
        """解析 ioc 加上 extra 条目后的配置。
        Parse ioc with the extra entries appended.
        """
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "demo.ioc"
            path.write_text(ioc + extra, encoding="utf-8")
            return peripheral_analyzer_stm32.parse_ioc_file(str(path))

    def test_dma_priorities_keep_their_values(self):
        # DMA 优先级有 VERY_HIGH 一级。
        # DMA priorities have a VERY_HIGH level.
        parsed = self.parse(
            "Dma.USART1_RX.0.Priority=DMA_PRIORITY_VERY_HIGH\n"
            "Dma.USART1_TX.1.Priority=DMA_PRIORITY_LOW\n"
        )
        configurations = parsed["DMA"]["Configurations"]
        self.assertEqual(configurations["USART1_RX_0"]["priority"], "VeryHigh")
        self.assertEqual(configurations["USART1_TX_1"]["priority"], "Low")

    def test_fmpi2c_is_not_taken_for_i2c(self):
        # LibXR 没有 FMPI2C 驱动；当成 I2C 会生成类型不符的 I2C_HandleTypeDef 句柄。
        # LibXR has no FMPI2C driver; taken for I2C it would get a mistyped I2C_HandleTypeDef.
        with self.assertLogs(level="WARNING") as logs:
            peripherals = self.parse("PC6.Signal=FMPI2C1_SCL\nPC7.Signal=FMPI2C1_SDA\n")[
                "Peripherals"
            ]
        self.assertNotIn("I2C", peripherals)
        fmpi2c = [line for line in logs.output if "FMPI2C1" in line]
        self.assertEqual(
            fmpi2c, ["WARNING:root:FMPI2C1 is not generated: LibXR has no driver for it"]
        )

    def test_a_dac_entry_without_a_comma_is_skipped(self):
        with self.assertLogs(level="WARNING") as logs:
            parsed = self.parse("SH.COMP_DAC1_group.0=DAC_OUT1\n")
        self.assertIsNotNone(parsed)
        self.assertIn(
            "WARNING:root:Ignored DAC entry without a channel and an alias: "
            "SH.COMP_DAC1_group.0=DAC_OUT1",
            logs.output,
        )

    def test_a_parse_error_logs_its_traceback_at_debug_level(self):
        with (
            mock.patch.object(
                peripheral_analyzer_stm32.TIMParser, "parse", side_effect=RuntimeError("boom")
            ),
            self.assertLogs(level="DEBUG") as logs,
        ):
            self.assertIsNone(self.parse(""))
        errors = [r for r in logs.records if r.levelname == "ERROR"]
        self.assertEqual([r.getMessage() for r in errors], ["Parsing failed: boom"])
        self.assertIsNotNone(logs.records[-1].exc_info)

    def test_dma_requests_add_no_empty_peripheral_groups(self):
        peripherals = self.parse("")["Peripherals"]
        self.assertEqual(peripherals["USART"]["USART1"]["DMA_RX"], "ENABLE")
        self.assertNotIn("ADC", peripherals)
        self.assertNotIn("I2C", peripherals)

    def test_fields_come_from_their_own_properties(self):
        # STM32CubeH5 例程 UART_AutoBaudrate_Detection 用默认波特率，不写 BaudRate；以前
        # AutoBaudRateEnableParam 被当作波特率，摘要显示 BaudRate=UART_ADVFEATURE_AUTOBAUDRATE_ENABLE。
        # UART_AutoBaudrate_Detection of STM32CubeH5 keeps the default baud rate and writes no
        # BaudRate; AutoBaudRateEnableParam used to be taken for it, and the summary showed
        # BaudRate=UART_ADVFEATURE_AUTOBAUDRATE_ENABLE.
        peripherals = self.parse(
            "Mcu.IP8=UART4\nMcu.IP9=FDCAN1\n"
            "UART4.AutoBaudRateEnableParam=UART_ADVFEATURE_AUTOBAUDRATE_ENABLE\n"
            "SPI1.BaudRatePrescaler=SPI_BAUDRATEPRESCALER_32\n"
            "FDCAN1.Mode=FDCAN_MODE_NORMAL\nFDCAN1.TxFifoQueueMode=FDCAN_TX_FIFO_OPERATION\n"
        )["Peripherals"]
        self.assertNotIn("BaudRate", peripherals["USART"]["UART4"])
        self.assertNotIn("BaudRate", peripherals["SPI"]["SPI1"])
        self.assertEqual(peripherals["FDCAN"]["FDCAN1"]["Mode"], "FDCAN_MODE_NORMAL")

    def test_watchdogs_are_listed_once_with_their_values(self):
        # 以前看门狗在外设列表和单独的看门狗段各出现一次，外设列表那一行没有数值。
        # Watchdogs used to appear in the peripheral list and again in a separate watchdog
        # section, the peripheral line without values.
        with self.assertLogs(level="WARNING"):
            parsed = self.parse("", H5_IOC)
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            peripheral_analyzer_stm32.print_summary(parsed)
        self.assertEqual(
            output.getvalue().split("Active Peripherals:\n")[1],
            "  USART: 1 instance(s)\n"
            "    USART1: BaudRate=9600\n"
            "  IWDG: 1 instance(s)\n"
            "    IWDG: Enabled=True | Prescaler=IWDG_PRESCALER_64 | Reload=4095\n",
        )


class ChannelDma(TestCase):
    """GPDMA、HPDMA、LPDMA 的通道请求打开外设的 DMA 开关（生成器据此分配缓冲区）。
    Channel requests of GPDMA, HPDMA and LPDMA set the DMA flags of a peripheral, from which
    the generator allocates its buffers.
    """

    def parse(self, ioc):
        """解析 ioc 并返回配置；忽略 SysTick 时基的警告。
        Parse ioc and return the configuration; the SysTick timebase warning is ignored.
        """
        with self.assertLogs(level="WARNING") as self.logs:
            return ParsedConfiguration.parse(self, "", ioc)

    def test_gpdma_requests_set_the_uart_dma_flags(self):
        # 以前只读 Dma.RequestN，H5 的 USART1 没有 DMA 开关，生成为 STM32UART usart1(&huart1,
        # {nullptr, 0}, {nullptr, 0}, 5)。
        # Only Dma.RequestN used to be read; USART1 of the H5 had no DMA flags and became
        # STM32UART usart1(&huart1, {nullptr, 0}, {nullptr, 0}, 5).
        parsed = self.parse(H5_IOC)
        usart1 = parsed["Peripherals"]["USART"]["USART1"]
        self.assertEqual((usart1["DMA_TX"], usart1["DMA_RX"]), ("ENABLE", "ENABLE"))
        self.assertEqual(
            usart1["dma"]["dma_tx"],
            {
                "request_id": "GPDMACH0",
                "peripheral": "USART1_TX",
                "dma_type": "GPDMA",
                "stream": "GPDMA1_Channel0",
                "direction_full": "memory_to_periph",
            },
        )
        self.assertEqual(usart1["dma"]["dma_rx"]["stream"], "GPDMA1_Channel1")
        self.assertEqual(
            parsed["DMA"]["Requests"],
            {"GPDMA1.GPDMACH0": "USART1_TX", "GPDMA1.GPDMACH1": "USART1_RX"},
        )

    def test_hpdma_and_lpdma_requests_are_read_as_well(self):
        ioc = H5_IOC.replace("GPDMA1.REQUEST_GPDMACH0=GPDMA1_REQUEST_USART1_TX", "").replace(
            "GPDMA1.REQUEST_GPDMACH1=GPDMA1_REQUEST_USART1_RX",
            "HPDMA1.REQUEST_HPDMACH3=HPDMA1_REQUEST_USART1_TX\n"
            "LPDMA1.REQUEST_LPDMACH0=LPDMA1_REQUEST_USART1_RX",
        )
        usart1 = self.parse(ioc)["Peripherals"]["USART"]["USART1"]
        self.assertEqual(
            [(d["dma_type"], d["stream"]) for d in usart1["dma"].values()],
            [("HPDMA", "HPDMA1_Channel3"), ("LPDMA", "LPDMA1_Channel0")],
        )

    def test_linked_list_requests_are_warned_about(self):
        # 链表模式的请求在 Linkedlist.<通道>.<队列>.<节点>.Requestforcodegen 中，不读取。
        # Linked-list requests are in Linkedlist.<channel>.<queue>.<node>.Requestforcodegen
        # and are not read.
        ioc = H5_IOC.replace(
            "GPDMA1.REQUEST_GPDMACH0=GPDMA1_REQUEST_USART1_TX\n"
            "GPDMA1.REQUEST_GPDMACH1=GPDMA1_REQUEST_USART1_RX\n",
            "Linkedlist.MDMA_Channel0.GP_SW.0.Requestforcodegen=GPDMA1_REQUEST_USART1_TX\n"
            "Linkedlist.MDMA_Channel0.GP_SW.1.Requestforcodegen=GPDMA1_REQUEST_USART1_TX\n"
            "Linkedlist.MDMA_Channel1.GP_SW.0.Requestforcodegen=GPDMA1_REQUEST_USART1_RX\n",
        )
        usart1 = self.parse(ioc)["Peripherals"]["USART"]["USART1"]
        self.assertEqual(("DMA_TX" in usart1, "DMA_RX" in usart1), (False, False))
        self.assertIn(
            "WARNING:root:DMA requests in linked-list mode are not read: USART1_RX, USART1_TX; "
            "these peripherals get no DMA buffers",
            self.logs.output,
        )

    def test_simple_requests_give_no_linked_list_warning(self):
        self.parse(H5_IOC)
        self.assertEqual([line for line in self.logs.output if "linked-list" in line], [])


class HandleModes(TestCase):
    """模式决定 CubeMX 生成哪种 HAL 句柄；没有 LibXR 所需句柄的实例不生成。
    The mode decides which HAL handle CubeMX generates; an instance without the handle LibXR
    needs is not generated.
    """

    parse = ParsedConfiguration.parse

    def test_a_synchronous_usart_is_not_generated(self):
        # 以前照样生成 STM32UART usart1(&huart1, …)，工程里没有 huart1，链接失败。
        # STM32UART usart1(&huart1, ...) used to be generated; the project has no huart1 and
        # fails to link.
        with self.assertLogs(level="WARNING") as logs:
            peripherals = self.parse("", SYNC_USART_IOC)["Peripherals"]
        self.assertNotIn("USART", peripherals)
        self.assertIn(
            "WARNING:root:USART1 is not generated: Synchronous Slave mode uses "
            "USART_HandleTypeDef, and LibXR's STM32UART needs a UART handle",
            logs.output,
        )

    def test_a_smbus_i2c_is_not_generated(self):
        with self.assertLogs(level="WARNING") as logs:
            peripherals = self.parse("", SMBUS_IOC)["Peripherals"]
        self.assertNotIn("I2C", peripherals)
        self.assertIn(
            "WARNING:root:I2C2 is not generated: SMBus mode uses SMBUS_HandleTypeDef, and "
            "LibXR's STM32I2C needs an I2C handle",
            logs.output,
        )

    def test_a_peripheral_only_assigned_to_pins_is_not_generated(self):
        # STM32CubeH5 的 Nx_MQTT_Client 把 PD8 分配为 USART3_TX，但没有启用 USART3；以前照样
        # 生成 extern UART_HandleTypeDef huart3，链接失败。
        # Nx_MQTT_Client of STM32CubeH5 assigns PD8 to USART3_TX without enabling USART3;
        # extern UART_HandleTypeDef huart3 used to be generated anyway and failed to link.
        with self.assertLogs(level="WARNING") as logs:
            usart = self.parse("PD8.Signal=USART3_TX\n", H5_IOC)["Peripherals"]["USART"]
        self.assertEqual(list(usart), ["USART1"])
        self.assertIn(
            "WARNING:root:USART3 is not generated: it is not enabled in CubeMX (no Mcu.IP entry)",
            logs.output,
        )

    def test_project_manager_settings_decide_the_handle(self):
        # 条目取自 STM32CubeH5 例程：ADC_MultiChannel_UART（取消 Generate Code）、USBPD_SNK
        # （LL 驱动）和 Ux_Device_CDC_ACM（Do Not Generate Function Call）。
        # Entries from STM32CubeH5 examples: ADC_MultiChannel_UART (Generate Code off),
        # USBPD_SNK (LL driver) and Ux_Device_CDC_ACM (Do Not Generate Function Call).
        functions = "ProjectManager.functionlistsort=1-SystemClock_Config-RCC-false-HAL-false,"
        for entry, kept, message in (
            (
                "false-5-MX_USART1_UART_Init-USART1-true-HAL-true",
                False,
                "USART1 is not generated: Generate Code is off for it in the CubeMX Project "
                "Manager",
            ),
            (
                "5-MX_USART1_UART_Init-USART1-false-LL-true",
                False,
                "USART1 is not generated: it uses the LL driver in CubeMX, and LibXR needs a HAL "
                "handle",
            ),
            (
                "4-MX_USART1_UART_Init-USART1-true-HAL-false",
                True,
                "USART1: main() does not call MX_USART1_UART_Init() (Do Not Generate Function "
                "Call is set in CubeMX); call it before app_main() constructs the LibXR object",
            ),
        ):
            with self.subTest(entry=entry), self.assertLogs(level="WARNING") as logs:
                peripherals = self.parse(functions + entry + "\n", H5_IOC)["Peripherals"]
                self.assertEqual("USART" in peripherals, kept)
                self.assertIn(f"WARNING:root:{message}", logs.output)

    def test_asynchronous_uarts_keep_their_mode(self):
        with self.assertLogs(level="WARNING"):
            h5 = self.parse("", H5_IOC)["Peripherals"]["USART"]["USART1"]
        f4 = self.parse("")["Peripherals"]["USART"]
        self.assertEqual(
            [h5["Mode"], f4["USART1"]["Mode"], f4["USART6"]["Mode"]], ["Asynchronous"] * 3
        )


class Timers(TestCase):
    """PWM 通道按 CubeMX 的通道模式记录。
    PWM channels follow the channel modes of CubeMX.
    """

    parse = ParsedConfiguration.parse

    def test_main_and_complementary_outputs_are_both_recorded(self):
        # 键取自 STM32CubeH5 例程 TIM_BreakAndDeadtime_Init；以前只记 CH1N，主输出 CH1 从不启动。
        # The key comes from the STM32CubeH5 example TIM_BreakAndDeadtime_Init; only CH1N used
        # to be recorded, and the main output CH1 was never started.
        channels = self.parse(
            "PA7.Signal=TIM1_CH1N\nTIM1.Channel-PWM\\ Generation1\\ CH1\\ CH1N=TIM_CHANNEL_1\n"
        )["Peripherals"]["TIM"]["TIM1"]["Channels"]
        self.assertEqual(
            {name: channel["Complementary"] for name, channel in channels.items()},
            {"CH1": False, "CH1N": True},
        )

    def test_a_single_channel_timer_follows_its_mode(self):
        # 单通道定时器不论什么模式都写 TIMx.Channel；以前一律当作 PWM。
        # A single-channel timer writes TIMx.Channel whatever its mode; it used to be taken
        # for PWM every time.
        for extra, pwm in (
            # STM32CubeH5 例程 RTC_LSI：引脚上的输入捕获。
            # STM32CubeH5 example RTC_LSI: input capture on a pin.
            ("SH.S_TIM16_CH1.0=TIM16_CH1,Input_Capture1_from_TI1\n", set()),
            # STM32CubeH5 例程 TIM_InputCapture_DMA：内部信号的输入捕获。
            # STM32CubeH5 example TIM_InputCapture_DMA: input capture from an internal signal.
            ("VP_TIM16_VS_NoInput1.Mode=Input_Capture1_from_TI1_REMAP_TIM16\n", set()),
            ("SH.S_TIM16_CH1.0=TIM16_CH1,PWM Generation1 CH1 CH1N\n", {"CH1", "CH1N"}),
            ("", {"CH1"}),
        ):
            with self.subTest(extra=extra):
                timers = self.parse("Mcu.IP8=TIM16\nTIM16.Channel=TIM_CHANNEL_1\n" + extra)[
                    "Peripherals"
                ]["TIM"]
                self.assertEqual(set(timers["TIM16"].get("Channels", {})), pwm)


class Exti(TestCase):
    """外部中断引脚所在 EXTI 线的中断应在 NVIC 中开启。
    The EXTI line of an external interrupt pin should have its interrupt enabled in NVIC.
    """

    parse = ParsedConfiguration.parse

    def test_an_exti_line_without_an_nvic_interrupt_is_warned_about(self):
        # IOC 中 PE12 的 EXTI15_10_IRQn 已开启；PF1 的 EXTI1_IRQn 没开，与 DevC 的 IMU_INT 相同。
        # IOC enables EXTI15_10_IRQn for PE12; EXTI1_IRQn of PF1 is not enabled, as for IMU_INT
        # of DevC.
        with self.assertLogs(level="WARNING") as logs:
            self.parse("PF1.GPIO_Label=IMU_INT\nPF1.Signal=GPXTI1\n")
        self.assertEqual(
            logs.output,
            [
                "WARNING:root:The HAL timebase is SysTick. In STM32CubeMX, set SYS > Timebase "
                "Source to a general-purpose timer (such as TIM6) and give its interrupt the "
                "highest preemption priority (0) in NVIC.",
                "WARNING:root:PF1 (IMU_INT) is an external interrupt pin, but no NVIC interrupt "
                "of EXTI line 1 is enabled; enable it in STM32CubeMX NVIC, or the interrupt goes "
                "to Default_Handler once EnableInterrupt() is called",
            ],
        )
        with self.assertLogs(level="WARNING") as logs:
            self.parse("PF1.Signal=GPXTI1\nNVIC.EXTI1_IRQn=true\\:5\\:0\\:true\\:false\\:true\n")
        self.assertNotIn("external interrupt", "\n".join(logs.output))


class UsbRoles(TestCase):
    """USB 实例记下 CubeMX 中的角色；USB_DRD_FS 系列的 USB 实例还记下 CubeMX 生成的 PCD 句柄名。
    A USB instance records its role in CubeMX; the USB instance of the USB_DRD_FS families also
    records the PCD handle name CubeMX generates.
    """

    parse = ParsedConfiguration.parse

    def test_the_drd_usb_of_stm32h5_records_its_role_and_handle(self):
        # STM32CubeH5 的 USBX 设备例程都定义 PCD_HandleTypeDef hpcd_USB_DRD_FS；以前两者都没有
        # 记下，生成的 hpcd_USB_FS 链接失败，主机模式也生成了设备对象。
        # The USBX device examples of STM32CubeH5 all define PCD_HandleTypeDef hpcd_USB_DRD_FS;
        # neither used to be recorded, the generated hpcd_USB_FS failed to link, and host mode
        # got a device object as well.
        for mode, role in (("Device_Only", "Device"), ("Host_Only", "Host")):
            ioc = (
                "Mcu.Family=STM32H5\nMcu.CPN=STM32H503RBT6\nMcu.IP0=USB\n"
                f"USB.IPParameters=VirtualMode\nUSB.VirtualMode={mode}\n"
            )
            with self.subTest(mode=mode), self.assertLogs(level="WARNING"):
                self.assertEqual(
                    self.parse("", ioc)["Peripherals"]["USB"],
                    {
                        "USB": {
                            "IPParameters": ["VirtualMode"],
                            "VirtualMode": mode,
                            "Role": role,
                            "PCDHandle": "hpcd_USB_DRD_FS",
                        }
                    },
                )

    def test_the_usb_drd_fs_ip_records_its_handle(self):
        # STM32G0B1 的 .ioc 中 USB 的 IP 名就是 USB_DRD_FS，参数全为默认值时只有 Mcu.IPn 一行；
        # 以前没有记下句柄，生成器也不生成 usb_fs。
        # The USB IP name in the .ioc file of the STM32G0B1 is USB_DRD_FS itself, and with every
        # parameter at its default only the Mcu.IPn line is there; the handle used not to be
        # recorded, and the generator generated no usb_fs either.
        ioc = "Mcu.Family=STM32G0\nMcu.CPN=STM32G0B1CBU6\nMcu.IP0=USB_DRD_FS\n"
        with self.assertLogs(level="WARNING"):
            usb = self.parse("", ioc)["Peripherals"]["USB"]
        self.assertEqual(usb, {"USB_DRD_FS": {"PCDHandle": "hpcd_USB_DRD_FS"}})

    def test_the_mode_of_a_profile_gives_the_role(self):
        # fixtures.IOC 中 USB_OTG_HS 只在 Device_Only_FS profile 下写了 VirtualMode。
        # USB_OTG_HS of fixtures.IOC writes VirtualMode only under the Device_Only_FS profile.
        usb = self.parse("")["Peripherals"]["USB"]
        self.assertEqual(
            usb["USB_OTG_HS"],
            {
                "IPParameters": ["VirtualMode-Device_Only_FS"],
                "Role": "Device",
                "profiles": {"Device_Only_FS": {"VirtualMode": "Device_Only_FS"}},
            },
        )
        self.assertEqual(usb["USB_OTG_FS"]["Role"], "Device")


class Rtos(TestCase):
    """FreeRTOS 和 ThreadX 的不同来源都写出对应的段，libxr gen 据此选择 LibXR 的系统。
    Every source of FreeRTOS and ThreadX gives its section, from which libxr gen selects the
    LibXR system.
    """

    parse = ParsedConfiguration.parse

    def test_every_source_gives_its_section(self):
        # 以前 X-CUBE-FREERTOS 扩展包的工程没有 FreeRTOS 段，libxr gen 按裸机生成。参数全为
        # 默认值时（如 STM32CubeH5 的 USBX 例程）.ioc 中只有 Mcu.IPn=THREADX。
        # Projects with the X-CUBE-FREERTOS pack used to get no FreeRTOS section, and libxr gen
        # generated for bare metal. With every parameter at its default, as in the USBX
        # examples of STM32CubeH5, the .ioc file only has Mcu.IPn=THREADX.
        for extra, section in (
            ("Mcu.ThirdParty0=STMicroelectronics.X-CUBE-FREERTOS.1.6.0\n", "FreeRTOS"),
            ("Mcu.IP9=FREERTOS\n", "FreeRTOS"),
            ("FREERTOS.configTOTAL_HEAP_SIZE=4096\n", "FreeRTOS"),
            ("Mcu.IP9=THREADX\n", "ThreadX"),
            ("THREADX.TX_APP_CREATION=1\n", "ThreadX"),
            (
                "STMicroelectronics.X-CUBE-AZRTOS-H7.3.3.0.AZRTOS_APP_MEM_ALLOCATION_METHOD=1\n",
                "ThreadX",
            ),
            ("", None),
        ):
            with self.subTest(extra=extra), self.assertLogs(level="WARNING"):
                parsed = self.parse(extra, H5_IOC)
                self.assertEqual(
                    {name: parsed[name] for name in ("FreeRTOS", "ThreadX") if name in parsed},
                    {section: {"Enabled": True}} if section else {},
                )

    def test_cmsis_v2_without_xtimerpendfunctioncall_needs_the_override(self):
        # MC02 的 .ioc 单独生成后编译报 freertos_os2.h 的 #error，以前 parse 不提示，只能靠用户
        # 代码中的覆盖块。
        # The .ioc of MC02 generated on its own used to fail with the #error of freertos_os2.h,
        # with no hint from parse; only an override block in user code fixed it.
        ioc = (
            "Mcu.IP9=FREERTOS\nFREERTOS.INCLUDE_xTimerPendFunctionCall=0\n"
            "Mcu.Pin52=VP_FREERTOS_VS_CMSIS_V2\nVP_FREERTOS_VS_CMSIS_V2.Mode=CMSIS_V2\n"
            "VP_FREERTOS_VS_CMSIS_V2.Signal=FREERTOS_VS_CMSIS_V2\n"
        )
        warning = [
            "WARNING:root:FreeRTOS uses CMSIS_V2 with INCLUDE_xTimerPendFunctionCall = 0, and "
            "Core/Inc/FreeRTOSConfig.h does not set configUSE_OS2_EVENTFLAGS_FROM_ISR to 0, so "
            'freertos_os2.h #error "Definition INCLUDE_xTimerPendFunctionCall must equal 1 to '
            'implement Event Flags API." stops the build. Override these definitions in the USER '
            "CODE BEGIN Defines section of Core/Inc/FreeRTOSConfig.h, which CubeMX keeps when it "
            "regenerates the code:",
            "WARNING:root:  /* USER CODE BEGIN Defines */",
            "WARNING:root:  #undef configUSE_TIMERS",
            "WARNING:root:  #define configUSE_TIMERS 0",
            "WARNING:root:  #undef configUSE_OS2_TIMER",
            "WARNING:root:  #define configUSE_OS2_TIMER 0",
            "WARNING:root:  #undef configUSE_OS2_EVENTFLAGS_FROM_ISR",
            "WARNING:root:  #define configUSE_OS2_EVENTFLAGS_FROM_ISR 0",
            "WARNING:root:  /* USER CODE END Defines */",
        ]
        # CubeMX 写出的 FreeRTOSConfig.h 中这个值为 1；覆盖块在 USER CODE BEGIN Defines 区中。
        # The FreeRTOSConfig.h CubeMX writes sets the value to 1; the override block is in the
        # USER CODE BEGIN Defines section.
        cubemx = "#define configUSE_OS2_EVENTFLAGS_FROM_ISR    1\n"
        override = cubemx + "\n".join(peripheral_analyzer_stm32.OS2_TIMER_OVERRIDES) + "\n"
        for config, extra, warned in (
            (None, ioc, True),
            (cubemx, ioc, True),
            (override, ioc, False),
            (None, ioc.replace("Mode=CMSIS_V2", "Mode=CMSIS_V1"), False),
            (None, ioc.replace("PendFunctionCall=0", "PendFunctionCall=1"), False),
        ):
            with self.subTest(config=config, extra=extra), tempfile.TemporaryDirectory() as root:
                path = Path(root) / "demo.ioc"
                path.write_text(H5_IOC + extra, encoding="utf-8")
                if config is not None:
                    (Path(root) / "Core" / "Inc").mkdir(parents=True)
                    (Path(root) / "Core" / "Inc" / "FreeRTOSConfig.h").write_text(
                        config, encoding="utf-8"
                    )
                with self.assertLogs(level="WARNING") as logs:
                    peripheral_analyzer_stm32.parse_ioc_file(str(path))
                found = [
                    line
                    for line in logs.output
                    if "CMSIS_V2" in line or line.startswith("WARNING:root:  ")
                ]
                self.assertEqual(found, warning if warned else [])


class Pins(TestCase):
    """引脚名 PxN 的端口字母从 A 到 Z。
    The port letter of a pin name PxN runs from A to Z.
    """

    parse = ParsedConfiguration.parse

    def test_stm32n6_ports_after_k_are_read(self):
        # CubeMX 的 STM32N6 引脚表有 PN0 等 PN～PQ 端口的引脚；以前只认 PA～PK，这些 GPIO 被丢掉。
        # The STM32N6 pin list of CubeMX has pins such as PN0 on ports PN to PQ; only PA to PK
        # used to be read, and these GPIOs were dropped.
        gpio = self.parse(
            "PN0.GPIO_Label=LED_N\nPN0.Signal=GPIO_Output\nPO1.GPIO_Label=KEY_O\nPO1.Signal=GPXTI1\n"
        )["GPIO"]
        self.assertEqual(
            {pin: gpio[pin] for pin in ("PN0", "PO1")},
            {
                "PN0": {"Label": "LED_N", "Signal": "GPIO_Output"},
                "PO1": {"Label": "KEY_O", "Signal": "GPXTI1", "GPXTI": True},
            },
        )


class RegularConversions(TestCase):
    """ADC 规则通道按 rank 排列，同一通道在几个 rank 中就出现几次；DMA 模式下生成器按这个顺序
    读 DMA 缓冲区。
    ADC regular channels follow their ranks, a channel appearing once per rank it is in; in DMA
    mode the generator reads the DMA buffer in this order.
    """

    def parse(self, ioc):
        """解析 ioc 并返回 ADC3 的配置；忽略 SysTick 时基的警告。
        Parse ioc and return the configuration of ADC3; the SysTick timebase warning is
        ignored.
        """
        with self.assertLogs(level="WARNING"):
            return ParsedConfiguration.parse(self, "", ioc)["Peripherals"]["ADC"]["ADC3"]

    def test_ranks_follow_their_numbers_not_the_key_order(self):
        # 以前按 key 的文本顺序收集并去重，得到 IN8、1、15、2…14 共 11 个，第 3 个起都错位。
        # Channels used to be collected in key text order without repeats: IN8, 1, 15, 2 ... 14,
        # 11 of them, every one from the third on in the wrong slot.
        ranks = [8, 1, 2, 3, 5, 6, 7, 9, 13, 14, 15, 8]
        adc3 = self.parse(ADC_RANKS_IOC)
        self.assertEqual(adc3["RegularConversions"], [f"ADC_CHANNEL_{n}" for n in ranks])
        self.assertEqual(adc3["Channels"], [f"ADC_CHANNEL_{n}" for n in ranks[:-1]])

    def test_any_number_of_ranks_keeps_the_rank_order(self):
        for count in range(1, 17):
            with self.subTest(count=count):
                channels = [f"ADC_CHANNEL_{(7 * i + 3) % 16}" for i in range(count)]
                lines = [
                    rf"ADC3.Channel-{i}\#ChannelRegularConversion={channel}"
                    for i, channel in enumerate(channels)
                ]
                # CubeMX 按去掉转义后的 key 排序保存。
                # CubeMX saves the keys sorted with the escapes removed.
                lines.sort(key=lambda line: line.split("=")[0].replace("\\", ""))
                adc3 = self.parse("\n".join(lines) + "\nDma.Request0=ADC3\n")
                self.assertEqual(adc3["RegularConversions"], channels)


class Timebase(TestCase):
    """HAL 时基应是中断优先级最高的普通定时器，否则警告。
    The HAL timebase should be a general-purpose timer with the highest interrupt priority;
    anything else is warned about.
    """

    TIMER = "NVIC.TimeBase=TIM6_DAC_IRQn\nNVIC.TimeBaseIP=TIM6\n"
    parse = ParsedConfiguration.parse

    def test_systick_is_warned_about(self):
        with self.assertLogs(level="WARNING") as logs:
            self.assertEqual(self.parse("")["Timebase"], {"Source": "SysTick", "IRQ": None})
        self.assertEqual(
            logs.output,
            [
                "WARNING:root:The HAL timebase is SysTick. In STM32CubeMX, set SYS > Timebase "
                "Source to a general-purpose timer (such as TIM6) and give its interrupt the "
                "highest preemption priority (0) in NVIC."
            ],
        )

    def test_a_timer_needs_the_highest_priority(self):
        with self.assertLogs(level="WARNING") as logs:
            timebase = self.parse(self.TIMER + "NVIC.TIM6_DAC_IRQn=true\\:5\\:0\\:false\\:true\n")
        self.assertEqual(timebase["Timebase"], {"Source": "TIM6", "IRQ": "TIM6_DAC_IRQn"})
        self.assertEqual(
            logs.output,
            [
                "WARNING:root:The HAL timebase interrupt TIM6_DAC_IRQn (TIM6) has preemption "
                "priority 5. In STM32CubeMX, set it to the highest (0) in NVIC."
            ],
        )
        with self.assertNoLogs(level="WARNING"):
            self.parse(self.TIMER + "NVIC.TIM6_DAC_IRQn=true\\:0\\:0\\:false\\:true\n")


if __name__ == "__main__":
    unittest.main()
