#!/usr/bin/env python
"""libxr stm32 cmake：把 LibXR 接入 CubeMX 生成的 CMake 工程。
libxr stm32 cmake: integrate LibXR into a CMake project generated by CubeMX.

整体生成 cmake/LibXR.CMake，把 ST Arm Clang 工具链文件恢复为 CubeMX 原样，并在 CMakeLists.txt
中 include LibXR.CMake。这些文件改变后，已有的构建目录在下次构建时由 CMake 重新配置。
It generates cmake/LibXR.CMake as a whole, restores the ST Arm Clang toolchain file to what
CubeMX wrote, and includes LibXR.CMake from CMakeLists.txt. CMake reconfigures existing build
directories on their next build after these files change.

LibXR.CMake 的结构固定：“Project settings”块在最前，其后依次是 LibXR、Application、库的优化
设置和固件镜像（链接后由 ELF 生成 .hex 和 .bin）。重写时保留 “Project settings” 块中用户改过的
值；已有的旧格式文件迁移到这个结构，设置的值和用到的优化级别都保留，不认识的语句放在末尾的
“Kept” 块中保留。
The structure of LibXR.CMake is fixed: the "Project settings" block comes first, followed by
LibXR, Application, the optimization of the libraries and the firmware images (the .hex and
.bin made from the ELF after linking). Rewriting keeps the values the user changed in the
"Project settings" block; a file in an earlier format migrates to this structure, keeping the
values of the settings and the optimization levels it uses, and the statements it does not
recognize are kept in a "Kept" block at the end.
"""

import logging
import os
import re
import sys
from pathlib import Path

from xr_syntax.cpp import CppDocument
from xr_syntax.i18n import tr

from libxr import cmake_text

# LibXR.CMake 第一行：说明文件由 libxr stm32 setup 生成，只有设置块供用户修改。
# The first line of LibXR.CMake: the file is generated by libxr stm32 setup, and only the
# settings block is for the user to edit.
GENERATED_LINE = (
    '# Generated by `libxr stm32 setup`; edit the values in the "Project settings" block only.'
)
# 块标题的宽度。
# The width of the block titles.
RULE_WIDTH = 80
SETTINGS_TITLE = "Project settings"
LIBXR_TITLE = "LibXR"
APPLICATION_TITLE = "Application"
OPTIMIZATION_TITLE = "Library optimization"
FIRMWARE_TITLE = "Firmware images"
KEPT_TITLE = "Kept from the earlier LibXR.CMake"
# 新工程的默认优化级别：应用代码在 Debug 构建中的级别和 Release 构建的级别；空字符串表示沿用
# 工具链文件中的级别（CubeMX 写出的 gcc 为 -Os，ST Arm Clang 为 -Oz）。
# The default optimization levels of a new project: that of the application code in Debug builds
# and that of Release builds; an empty string keeps the level of the toolchain file (-Os for gcc
# and -Oz for ST Arm Clang as CubeMX writes them).
DEFAULT_OPT_DEBUG = "-Og"
DEFAULT_OPT_RELEASE = ""
# “Project settings” 块中 User 源文件的默认写法；写成空字符串表示由 CMakeLists.txt 自己加入。
# The default of the User sources in the "Project settings" block; an empty string means that
# CMakeLists.txt adds them itself.
USER_SOURCES_GLOB = "${CMAKE_CURRENT_SOURCE_DIR}/User/*.cpp"
# XRobot 工程在 “Project settings” 块中设置的模块目录。
# The Modules directory that an XRobot project sets in the "Project settings" block.
XROBOT_MODULES_DIR_LINE = 'set(XROBOT_MODULES_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Modules")'

LIBXR_BLOCK = """\
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(LIBXR_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/Third_Party/LibXR"
    CACHE PATH "LibXR source directory")
add_subdirectory("${LIBXR_SOURCE_DIR}" "${CMAKE_CURRENT_BINARY_DIR}/LibXR")
target_link_libraries(xr PUBLIC stm32cubemx)
target_include_directories(xr PUBLIC Core/Inc User)
target_compile_features(xr PUBLIC cxx_std_20)"""

APPLICATION_BLOCK = """\
set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES CXX_STANDARD 20 CXX_STANDARD_REQUIRED ON)
if(LIBXR_USER_SOURCES_GLOB)
    file(GLOB LIBXR_USER_SOURCES CONFIGURE_DEPENDS "${LIBXR_USER_SOURCES_GLOB}")
    target_sources(${CMAKE_PROJECT_NAME} PRIVATE ${LIBXR_USER_SOURCES})
endif()
target_link_libraries(${CMAKE_PROJECT_NAME} xr)
# Target options follow CMAKE_<LANG>_FLAGS_<CONFIG> on the compile line, so the last -O decides.
target_compile_options(${CMAKE_PROJECT_NAME} PRIVATE
    $<$<CONFIG:Debug>:${LIBXR_OPT_DEBUG}> $<$<CONFIG:Release>:${LIBXR_OPT_RELEASE}>)"""

OPTIMIZATION_BLOCK = """\
# Debug builds keep xr and the CubeMX libraries optimized (-O2); Release builds compile them at
# LIBXR_OPT_RELEASE, like the application.
set(LIBXR_LIBRARIES xr)
if(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/cmake/stm32cubemx")
    get_directory_property(LIBXR_CUBEMX_TARGETS
        DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/cmake/stm32cubemx" BUILDSYSTEM_TARGETS)
    foreach(target IN LISTS LIBXR_CUBEMX_TARGETS)
        get_target_property(target_type ${target} TYPE)
        if(NOT target_type STREQUAL "INTERFACE_LIBRARY")
            list(APPEND LIBXR_LIBRARIES ${target})
        endif()
    endforeach()
endif()
foreach(library IN LISTS LIBXR_LIBRARIES)
    target_compile_options(${library} PRIVATE
        $<$<CONFIG:Debug>:-O2> $<$<CONFIG:Release>:${LIBXR_OPT_RELEASE}>)
endforeach()"""

# 链接后由 ELF 生成 <工程名>.hex（Intel HEX）和 <工程名>.bin（二进制镜像），与 ELF 在同一目录；
# CMAKE_OBJCOPY 来自 CubeMX 的工具链文件。
# After linking, <project>.hex (Intel HEX) and <project>.bin (binary image) are made from the ELF
# in its directory; CMAKE_OBJCOPY comes from the CubeMX toolchain file.
FIRMWARE_BLOCK = """\
# Each link of the application also writes <project>.hex and <project>.bin next to the ELF.
add_custom_command(TARGET ${CMAKE_PROJECT_NAME} POST_BUILD
    WORKING_DIRECTORY $<TARGET_FILE_DIR:${CMAKE_PROJECT_NAME}>
    COMMAND ${CMAKE_OBJCOPY} --output-target ihex
        $<TARGET_FILE_NAME:${CMAKE_PROJECT_NAME}> ${CMAKE_PROJECT_NAME}.hex
    COMMAND ${CMAKE_OBJCOPY} --output-target binary --strip-all
        $<TARGET_FILE_NAME:${CMAKE_PROJECT_NAME}> ${CMAKE_PROJECT_NAME}.bin
    VERBATIM)"""

include_cmake_cmd = "include(${CMAKE_CURRENT_LIST_DIR}/cmake/LibXR.CMake)\n"

# 非注释行中任意写法的 include(...LibXR.CMake)。
# An include(...LibXR.CMake) in any spelling on a line that is not a comment.
_LIBXR_CMAKE_INCLUDE = re.compile(
    r"^[ \t]*include[ \t]*\([^)#\n]*LibXR\.CMake[^)\n]*\)", re.IGNORECASE | re.MULTILINE
)


def includes_libxr_cmake(content: str) -> bool:
    """CMakeLists.txt 的内容 content 是否已经 include LibXR.CMake。
    Whether content, the text of a CMakeLists.txt, already includes LibXR.CMake.

    include 的路径写法和大小写不限，最后一行没有换行也算；被注释掉的行不算。只比较整行文字时，
    这些写法会被再追加一次 include，LibXR 随之被 add_subdirectory 两次，CMake 配置失败。
    Any spelling of the path and any case count, also on a last line without a newline; a
    commented-out line does not. Comparing whole lines would append a second include for these
    spellings, and LibXR would then be added twice and fail the CMake configure.
    """
    return _LIBXR_CMAKE_INCLUDE.search(content) is not None


def project_uses_xrobot(input_directory: str) -> bool:
    """User/app_main.cpp 由 --xrobot 生成时为真；文件不存在时为假。
    True when User/app_main.cpp was generated with --xrobot; False when the file is missing.

    libxr stm32 setup 在接入 CMake 之前生成该文件。
    libxr stm32 setup generates that file before the CMake integration.
    """
    return uses_xrobot(os.path.join(input_directory, "User", "app_main.cpp"))


def uses_xrobot(app_main: str) -> bool:
    """源文件 app_main 由 libxr gen --xrobot 生成时为真；文件不存在时为假。
    True when the source file app_main was generated by libxr gen --xrobot; False when the
    file is missing.

    libxr gen --xrobot 在 User Code 区域之外 include xrobot_main.hpp。
    libxr gen --xrobot includes xrobot_main.hpp outside the User Code regions.
    """
    if not os.path.isfile(app_main):
        return False
    document = CppDocument.parse(read_text_with_fallback(app_main))
    regions = [region.body_span for region in document.user_regions()]
    for include in document.include_views():
        start = include.node.span.start
        if include.header == "xrobot_main.hpp" and not any(
            span.start <= start < span.end for span in regions
        ):
            return True
    return False


def read_text_with_fallback(path: str) -> str:
    """依次尝试以 UTF-8、UTF-8-SIG 和 GB18030 解码读取文本文件，返回第一个成功的结果。
    Read a text file with the first of UTF-8, UTF-8-SIG and GB18030 that decodes it.

    Raises:
        UnicodeDecodeError: 三种编码都无法解码该文件。
            None of the three encodings decodes the file.
    """
    for enc in ("utf-8", "utf-8-sig", "gb18030"):
        try:
            return Path(path).read_text(encoding=enc)
        except UnicodeDecodeError:
            continue
    return Path(path).read_text(encoding="utf-8")


# --------------------------
# LibXR.CMake 的结构 / Structure of LibXR.CMake
# --------------------------
def _rule(title: str) -> str:
    """块标题行：# ---- <title> ---- 补满 RULE_WIDTH 列。
    A block title line: # ---- <title> followed by dashes up to RULE_WIDTH columns.
    """
    head = f"# ---- {title} "
    return head + "-" * max(4, RULE_WIDTH - len(head))


def render_libxr_cmake(settings: str, kept: str = "") -> str:
    """LibXR.CMake 的完整内容：settings 是 “Project settings” 块的内容，kept 是末尾 “Kept” 块的
    内容（为空时没有这个块）。
    The complete content of LibXR.CMake: settings is the content of the "Project settings"
    block and kept the content of the "Kept" block at the end (without that block when empty).
    """
    parts = [
        GENERATED_LINE,
        "",
        _rule(SETTINGS_TITLE),
        settings.strip("\n"),
        "",
        _rule(LIBXR_TITLE),
        LIBXR_BLOCK,
        "",
        _rule(APPLICATION_TITLE),
        APPLICATION_BLOCK,
        "",
        _rule(OPTIMIZATION_TITLE),
        OPTIMIZATION_BLOCK,
        "",
        _rule(FIRMWARE_TITLE),
        FIRMWARE_BLOCK,
    ]
    if kept.strip():
        parts += ["", _rule(KEPT_TITLE), kept.strip("\n")]
    return "\n".join(parts) + "\n"


def _setting_lines(opt_debug: str, opt_release: str, user_sources: str) -> list[str]:
    """“Project settings” 块中 LIBXR_USER_SOURCES_GLOB、LIBXR_OPT_DEBUG 和 LIBXR_OPT_RELEASE 的
    设置行，前两项带说明注释。
    The setting lines of LIBXR_USER_SOURCES_GLOB, LIBXR_OPT_DEBUG and LIBXR_OPT_RELEASE in the
    "Project settings" block, the first two with their comment.
    """
    return [
        '# User sources of the application; "" when CMakeLists.txt adds them itself.\n'
        f'set(LIBXR_USER_SOURCES_GLOB "{user_sources}")',
        "# Optimization level of the application in Debug builds and of everything in Release "
        'builds;\n# "" keeps the level of the toolchain file.\n'
        f'set(LIBXR_OPT_DEBUG "{opt_debug}")',
        f'set(LIBXR_OPT_RELEASE "{opt_release}")',
    ]


def default_settings(system: str, opt_debug: str, opt_release: str) -> str:
    """新工程的 “Project settings” 块：LIBXR_SYSTEM、LIBXR_DRIVER、User 源文件和两个优化级别。
    The "Project settings" block of a new project: LIBXR_SYSTEM, LIBXR_DRIVER, the User sources
    and the two optimization levels.
    """
    lines = [f"set(LIBXR_SYSTEM {system})", "set(LIBXR_DRIVER st)"]
    lines += _setting_lines(opt_debug, opt_release, USER_SOURCES_GLOB)
    return "\n".join(lines) + "\n"


def split_blocks(content: str) -> dict[str, str] | None:
    """新格式 LibXR.CMake 的各块：{标题: 内容}；第一行不是 GENERATED_LINE（旧格式）时为 None。
    The blocks of a LibXR.CMake in the current format as {title: content}; None when the first
    line is not GENERATED_LINE, an earlier format.
    """
    lines = content.split("\n")
    if not lines or lines[0].strip() != GENERATED_LINE:
        return None
    blocks: dict[str, list[str]] = {}
    current = None
    for line in lines[1:]:
        title = re.fullmatch(r"# ---- (.+?) -{4,}", line.rstrip())
        if title:
            current = title.group(1)
            blocks[current] = []
        elif current is not None:
            blocks[current].append(line)
    return {title: "\n".join(body).strip("\n") for title, body in blocks.items()}


# set(<name> <value>) 的写法：值取到右括号或行尾的注释之前。
# The spelling of set(<name> <value>): the value runs up to the closing parenthesis or a
# comment at the end of the line.
def _setting(name: str) -> re.Pattern:
    """匹配设置块中 set(name ...) 一行的正则；第 1 组为 set( 和名字，第 2 组为值。
    The regular expression for a set(name ...) line of the settings block; group 1 is set( and
    the name, group 2 the value.
    """
    return re.compile(rf"^([ \t]*set[ \t]*\([ \t]*{name}[ \t]+)([^)#\n]*?)([ \t]*\))", re.MULTILINE)


def _set_system(settings: str, system: str) -> str:
    """把设置块中所有 set(LIBXR_SYSTEM ...) 的值换成 system；没有这一行时插在块的开头。
    Replace the value of every set(LIBXR_SYSTEM ...) of the settings block with system; the
    line is inserted at the top of the block when it is missing.
    """
    pattern = _setting("LIBXR_SYSTEM")
    if pattern.search(settings):
        return pattern.sub(lambda m: f"{m.group(1)}{system}{m.group(3)}", settings)
    return f"set(LIBXR_SYSTEM {system})\n" + settings


def _add_missing(settings: str, name: str, line: str, after: str | None = None) -> str:
    """设置块中没有 set(name ...) 时加入 line：放在 set(after ...) 之后，没有 after 时放在块的末尾。
    Add line when the settings block has no set(name ...): after set(after ...), or at the end
    of the block without after.
    """
    if _setting(name).search(settings):
        return settings
    if after:
        match = _setting(after).search(settings)
        if match:
            end = settings.find("\n", match.end())
            end = len(settings) if end < 0 else end + 1
            return settings[:end] + line + "\n" + settings[end:]
    return settings.rstrip("\n") + "\n" + line + "\n"


def _follow_xrobot_choice(settings: str, use_xrobot: bool, line: str = "") -> str:
    """让设置块中的 XROBOT_MODULES_DIR 与入口源文件的选择一致，返回新内容。
    Make XROBOT_MODULES_DIR in the settings block agree with the choice of the entry source and
    return the new content.

    使用 XRobot 而没有这一设置时，在 LIBXR_DRIVER 之后加入 line（默认 XROBOT_MODULES_DIR_LINE）；
    不使用 XRobot 而有这一设置时删除它。每次改动都记录一条说明。
    With XRobot and no such setting, line (XROBOT_MODULES_DIR_LINE by default) is added after
    LIBXR_DRIVER; without XRobot, an existing setting is removed. Each change is logged.
    """
    line = line or XROBOT_MODULES_DIR_LINE
    setting = re.compile(r"^[ \t]*set\s*\(\s*XROBOT_MODULES_DIR\b[^\n]*\n?", re.MULTILINE)
    if use_xrobot and not setting.search(settings):
        logging.info(
            tr(
                f"LibXR.CMake: added {line}, as User/app_main.cpp uses XRobot",
                f"LibXR.CMake：User/app_main.cpp 使用了 XRobot，已加入 {line}",
            )
        )
        return _add_missing(settings, "XROBOT_MODULES_DIR", line, "LIBXR_DRIVER")
    if not use_xrobot and setting.search(settings):
        logging.info(
            tr(
                "LibXR.CMake: removed XROBOT_MODULES_DIR, as User/app_main.cpp does not use XRobot",
                "LibXR.CMake：User/app_main.cpp 没有使用 XRobot，已删除 XROBOT_MODULES_DIR",
            )
        )
        return setting.sub("", settings)
    return settings


def _complete_settings(
    settings: str,
    system: str,
    use_xrobot: bool,
    opt_debug: str,
    opt_release: str,
    xrobot_line: str = "",
) -> str:
    """补全并校正设置块：LIBXR_SYSTEM 取检测到的系统，缺少的 LIBXR_DRIVER 和优化级别补上默认值，
    XROBOT_MODULES_DIR 与入口源文件的选择一致；其余内容不动。
    Complete and correct the settings block: LIBXR_SYSTEM takes the detected system, a missing
    LIBXR_DRIVER or optimization level gets its default, XROBOT_MODULES_DIR agrees with the
    choice of the entry source, and everything else stays.
    """
    settings = _set_system(settings, system)
    settings = _add_missing(settings, "LIBXR_DRIVER", "set(LIBXR_DRIVER st)", "LIBXR_SYSTEM")
    settings = _follow_xrobot_choice(settings, use_xrobot, xrobot_line)
    sources, debug, release = _setting_lines(opt_debug, opt_release, USER_SOURCES_GLOB)
    settings = _add_missing(settings, "LIBXR_USER_SOURCES_GLOB", sources)
    settings = _add_missing(settings, "LIBXR_OPT_DEBUG", debug)
    return _add_missing(settings, "LIBXR_OPT_RELEASE", release)


# --------------------------
# 旧格式的迁移 / Migration of the earlier format
# --------------------------
# 旧模板中、迁移时可以丢弃的语句（空白折叠后的写法）：新结构会重新生成它们。
# The statements of the earlier templates that migration may drop, in their whitespace-collapsed
# spelling: the new structure generates them again.
_TEMPLATE_STATEMENTS = frozenset(
    {
        "target_link_libraries(xr PUBLIC stm32cubemx)",
        "target_compile_features(xr PUBLIC cxx_std_20)",
        "target_include_directories(xr PUBLIC $<TARGET_PROPERTY:stm32cubemx,INTERFACE_INCLUDE_DIRECTORIES> "
        "PUBLIC Core/Inc PUBLIC User)",
        "set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES CXX_STANDARD 20 "
        "CXX_STANDARD_REQUIRED ON)",
        "target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE PUBLIC "
        "$<TARGET_PROPERTY:xr,INTERFACE_INCLUDE_DIRECTORIES> PUBLIC User)",
        "target_link_libraries(${CMAKE_PROJECT_NAME} stm32cubemx xr)",
        'file(GLOB LIBXR_USER_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/User/*.cpp")',
        'file(GLOB LIBXR_USER_SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/User/*.cpp")',
        "target_sources(${CMAKE_PROJECT_NAME} PRIVATE ${LIBXR_USER_SOURCES})",
    }
)
# 旧模板中会被重新生成的 set 语句。
# The set statements of the earlier templates that are generated again.
_TEMPLATE_VARIABLES = frozenset(
    {
        "CMAKE_CXX_STANDARD",
        "CMAKE_CXX_STANDARD_REQUIRED",
        "LIBXR_SYSTEM",
        "LIBXR_DRIVER",
        "XROBOT_MODULES_DIR",
        "LIBXR_SOURCE_DIR",
    }
)
_OPTIMIZATION = re.compile(r"-O(?:[0-3gsz]|fast)\b")
# 旧模板 Debug 块中库的默认选项（目标 PRIVATE -O2）；新结构的 “Library optimization” 块同样以
# -O2 编译它们，迁移时丢弃不必提示。
# The default library options of the Debug block of the earlier templates (target PRIVATE -O2);
# the "Library optimization" block of the new structure compiles them at -O2 too, so dropping
# them needs no notice.
_TEMPLATE_DEBUG_LIBRARIES = frozenset({"xr", "FreeRTOS", "STM32_Drivers", "USB_Device_Library"})
_USER_SOURCES_TARGET = "target_sources(${CMAKE_PROJECT_NAME} PRIVATE ${LIBXR_USER_SOURCES})"


def _user_sources_glob(arguments: list[str]) -> str | None:
    """file() 的参数 arguments 是否给 LIBXR_USER_SOURCES 收集文件：是 GLOB 且只有一个模式（可带
    CONFIGURE_DEPENDS）时返回这个模式，是 GLOB_RECURSE、多个模式或带其他选项时返回空字符串，
    不是收集 LIBXR_USER_SOURCES 的 file() 时返回 None。
    Whether the arguments of a file() call collect LIBXR_USER_SOURCES: the pattern for a GLOB with
    a single pattern (CONFIGURE_DEPENDS allowed), an empty string for GLOB_RECURSE, several
    patterns or other options, and None for a file() that does not collect LIBXR_USER_SOURCES.

    只有单一模式能写进 LIBXR_USER_SOURCES_GLOB；其余写法整条保留，见 migrate_libxr_cmake()。
    Only a single pattern fits LIBXR_USER_SOURCES_GLOB; any other spelling is kept as a whole, see
    migrate_libxr_cmake().
    """
    if len(arguments) < 2 or arguments[0] not in ("GLOB", "GLOB_RECURSE"):
        return None
    if arguments[1] != "LIBXR_USER_SOURCES":
        return None
    patterns = [argument for argument in arguments[2:] if argument != "CONFIGURE_DEPENDS"]
    if arguments[0] != "GLOB" or len(patterns) != 1:
        return ""
    return patterns[0].strip('"')


def _canonical(text: str) -> str:
    """语句去掉注释、折叠空白后的写法，括号内外的空白也规整，用来与旧模板比较。
    A statement without comments and with collapsed whitespace, the whitespace around the
    parentheses tidied too, for comparison with the earlier templates.
    """
    text = re.sub(r"#[^\n]*", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"\(\s+", "(", text)
    text = re.sub(r"\s+\)", ")", text)
    return re.sub(r"cxx_std_\d+", "cxx_std_20", text)


def _is_debug_block(text: str) -> bool:
    """text 是否是旧模板中 if(CMAKE_BUILD_TYPE STREQUAL "Debug") 的优化选项块。
    Whether text is the optimization block of the earlier templates that starts with
    if(CMAKE_BUILD_TYPE STREQUAL "Debug").

    块中只有 target_compile_options(<目标> PRIVATE -O<级别>) 和 if(TARGET <目标>) 才算。
    Only target_compile_options(<target> PRIVATE -O<level>) and if(TARGET <target>) count.
    """
    commands = cmake_text.commands(text)
    if not commands or _canonical(text[commands[0][2] : commands[0][3]]) != (
        'if(CMAKE_BUILD_TYPE STREQUAL "Debug")'
    ):
        return False
    for name, args, _, _ in commands[1:]:
        arguments = args.split()
        option = (
            name == "target_compile_options"
            and len(arguments) == 3
            and arguments[1] == "PRIVATE"
            and _OPTIMIZATION.fullmatch(arguments[2]) is not None
        )
        target_test = name == "if" and len(arguments) == 2 and arguments[0] == "TARGET"
        end = name == "endif" and not arguments
        if not (option or target_test or end):
            return False
    return True


def _migrate_debug_block(text: str) -> tuple[str | None, str]:
    """拆分旧模板的 Debug 块，返回 (应用目标的 -O 级别, 保留的 Debug 块)：没有应用目标的选项时
    级别为 None，没有要保留的选项时 Debug 块为空字符串。
    Split a Debug block of the earlier templates and return (the -O level of the application
    target, the kept Debug block): the level is None without an option for the application
    target, and the block is an empty string when no option is kept.

    旧模板默认的库选项（_TEMPLATE_DEBUG_LIBRARIES 中的目标 -O2）由新结构重新生成，不保留；用户
    改过的级别和加入的目标原样保留，连同包住它的 if(TARGET ...) 块，放进同一条件的 Debug 块中，
    每条记一条说明。保留的块写在 “Kept” 块中，排在 “Library optimization” 块之后，编译行上它的
    -O 在后，因此仍然生效。
    The default library options of the earlier templates (-O2 for the targets in
    _TEMPLATE_DEBUG_LIBRARIES) are generated again and not kept; levels the user changed and
    targets the user added are kept as written, with the if(TARGET ...) block around them, in a
    Debug block of the same condition, with one notice each. The kept block goes into the
    "Kept" block, after the "Library optimization" block, so its -O comes later on the compile
    line and still applies.
    """

    def line_start(offset: int) -> int:
        """offset 所在行的行首。
        The start of the line holding offset.
        """
        return text.rfind("\n", 0, offset) + 1

    commands = cmake_text.commands(text)
    app_debug = None
    kept: list[str] = []
    # 正在读的 if(TARGET ...) 的起点，以及其中是否有要保留的选项。
    # The start of the if(TARGET ...) being read, and whether it holds an option to keep.
    guard: int | None = None
    guard_kept = False
    for name, args, start, end in commands[1:-1]:
        if name == "if":
            guard, guard_kept = start, False
            continue
        if name == "endif":
            if guard is not None and guard_kept:
                kept.append(text[line_start(guard) : end])
            guard = None
            continue
        target, _, level = args.split()
        if target == "${CMAKE_PROJECT_NAME}":
            app_debug = level
            continue
        if target in _TEMPLATE_DEBUG_LIBRARIES and level == "-O2":
            continue
        option = f"target_compile_options({target} PRIVATE {level})"
        logging.info(
            tr(
                f"LibXR.CMake: kept {option} of the Debug block in the earlier file in the Kept "
                "block, after the -O2 that Debug builds now give xr and the CubeMX libraries",
                f"LibXR.CMake：已把旧文件 Debug 块中的 {option} 保留在 Kept 块中，位于 Debug 构建"
                "现在给 xr 和 CubeMX 生成的库的 -O2 之后",
            )
        )
        if guard is None:
            kept.append(text[line_start(start) : end])
        else:
            guard_kept = True
    if not kept:
        return app_debug, ""
    opening = text[commands[0][2] : commands[0][3]]
    closing = text[commands[-1][2] : commands[-1][3]]
    return app_debug, "\n".join([opening, *kept, closing])


def _toolchain_level(text: str, configuration: str) -> str | None:
    """工具链文件中 CMAKE_CXX_FLAGS_<配置> 的优化级别（如 -O3）；没有时为 None。
    The optimization level, such as -O3, of CMAKE_CXX_FLAGS_<configuration> in a toolchain file;
    None when there is none.
    """
    match = re.search(
        rf'set\s*\(\s*CMAKE_CXX_FLAGS_{configuration}\s+"([^"]*)"\s*\)', text, re.IGNORECASE
    )
    level = _OPTIMIZATION.search(match.group(1)) if match else None
    return level.group() if level else None


def toolchain_level(cmake_dir: str, configuration: str) -> str | None:
    """cmake 目录中工具链文件为配置 configuration（DEBUG 或 RELEASE）设置的优化级别。
    The optimization level the toolchain files in the cmake directory set for configuration,
    DEBUG or RELEASE.

    gcc-arm-none-eabi.cmake 和 starm-clang.cmake 的级别相同时返回该级别；都没有设置时返回 None；
    两个文件的级别不同时也返回 None，并记录一条说明：LIBXR_OPT_<配置> 留空，各工具链保持自己的级别。
    The level is returned when gcc-arm-none-eabi.cmake and starm-clang.cmake agree on it, and
    None when neither sets one; when the two files differ, None is returned as well and a notice
    is logged: LIBXR_OPT_<configuration> stays empty and each toolchain keeps its own level.
    """
    levels = {}
    for name in ("gcc-arm-none-eabi.cmake", "starm-clang.cmake"):
        path = os.path.join(cmake_dir, name)
        if not os.path.isfile(path):
            continue
        level = _toolchain_level(read_text_with_fallback(path), configuration)
        if level:
            levels[name] = level
    if len(set(levels.values())) > 1:
        described = ", ".join(f"{name} {level}" for name, level in levels.items())
        variable = f"LIBXR_OPT_{configuration}"
        logging.info(
            tr(
                f"The {configuration.capitalize()} levels of the toolchain files differ "
                f"({described}); {variable} stays empty and each toolchain keeps its own level",
                f"两个工具链文件的 {configuration.capitalize()} 优化级别不同（{described}）；"
                f"{variable} 留空，各工具链保持自己的级别",
            )
        )
        return None
    return next(iter(levels.values()), None)


def migrate_libxr_cmake(content: str, cmake_dir: str) -> tuple[str, str]:
    """把旧格式的 LibXR.CMake 迁移为新结构，返回 (“Project settings” 块, “Kept” 块)。
    Migrate a LibXR.CMake in an earlier format to the new structure and return (the "Project
    settings" block, the "Kept" block).

    保留旧文件的 LIBXR_DRIVER 和 XROBOT_MODULES_DIR；Debug 优化级别取旧文件中应用目标的 -O 选项，
    没有时取工具链文件的 Debug 级别，Release 级别取工具链文件的（见 toolchain_level()），再没有
    就留空，由各工具链文件决定，与迁移前相同。旧模板中会重新生成的语句被丢弃；Debug 块中用户改过
    的选项原样放进 “Kept” 块，每条记录一条说明（见 _migrate_debug_block()）。User 源文件的
    file(GLOB LIBXR_USER_SOURCES <模式>) 只有一个模式时写进 LIBXR_USER_SOURCES_GLOB；GLOB_RECURSE
    或多个模式时整条保留，与它的 target_sources 一起放进 “Kept” 块，LIBXR_USER_SOURCES_GLOB 为空。
    其余语句不丢：add_subdirectory(LibXR) 之前的放在设置块中，之后的放在 “Kept” 块中，并各记录
    一条说明。
    The old LIBXR_DRIVER and XROBOT_MODULES_DIR are kept; the Debug level is the -O option of the
    application target in the old file, or the Debug level of the toolchain files without one,
    and the Release level is that of the toolchain files (see toolchain_level()); without a level
    the setting stays empty and the toolchain files decide, as before the migration. The
    statements of the earlier templates that are generated again are dropped; options the user
    changed in the Debug block go into the "Kept" block as written, with a notice each (see
    _migrate_debug_block()).
    A file(GLOB LIBXR_USER_SOURCES <pattern>) of the User sources with a single pattern goes into
    LIBXR_USER_SOURCES_GLOB; a GLOB_RECURSE or several patterns are kept as a whole, together
    with their target_sources, in the "Kept" block, and LIBXR_USER_SOURCES_GLOB is empty. No other
    statement is lost: those before add_subdirectory(LibXR) go into the settings block and those
    after it into the "Kept" block, with a notice each.
    """
    driver = "st"
    modules_dir = None
    app_debug = None
    # 旧文件没有 file(GLOB LIBXR_USER_SOURCES ...) 时，User 源文件由 CMakeLists.txt 自己加入。
    # Without a file(GLOB LIBXR_USER_SOURCES ...) in the old file, CMakeLists.txt adds the User
    # sources itself.
    user_sources = ""
    before: list[str] = []
    after: list[str] = []
    parsed = cmake_text.statements(content)
    globs = [
        _user_sources_glob(statement.args.split())
        for statement in parsed
        if statement.name == "file"
    ]
    globs = [glob for glob in globs if glob is not None]
    # 只有一条单一模式的 file(GLOB ...) 时由 LIBXR_USER_SOURCES_GLOB 接管，它的 target_sources 随之
    # 丢弃；否则 file() 和 target_sources 都保留，User 源文件照旧加入工程。
    # Only a single file(GLOB ...) with one pattern is taken over by LIBXR_USER_SOURCES_GLOB,
    # and its target_sources is dropped with it; otherwise both file() and target_sources are
    # kept, and the User sources join the project as before.
    taken_over = len(globs) == 1 and bool(globs[0])
    if globs and not taken_over:
        logging.info(
            tr(
                "LibXR.CMake: the earlier file(... LIBXR_USER_SOURCES ...) is not a GLOB with a "
                "single pattern; it stays in the Kept block with its target_sources, and "
                'LIBXR_USER_SOURCES_GLOB is ""',
                "LibXR.CMake：旧文件中的 file(... LIBXR_USER_SOURCES ...) 不是单一模式的 GLOB，"
                '与它的 target_sources 一起保留在 Kept 块中，LIBXR_USER_SOURCES_GLOB 为 ""',
            )
        )
    library_at = next(
        (
            index
            for index, statement in enumerate(parsed)
            if statement.name == "add_subdirectory" and "LibXR" in statement.args
        ),
        None,
    )
    for index, statement in enumerate(parsed):
        text = content[statement.start : statement.end]
        arguments = statement.args.split()
        if statement.name == "set" and arguments and arguments[0] in _TEMPLATE_VARIABLES:
            if arguments[0] == "LIBXR_DRIVER" and len(arguments) > 1:
                driver = arguments[1]
            elif arguments[0] == "XROBOT_MODULES_DIR" and len(arguments) > 1:
                value = " ".join(arguments[1:])
                modules_dir = value if value.startswith('"') else f'"{value}"'
            continue
        if index == library_at:
            continue
        is_glob = statement.name == "file" and _user_sources_glob(arguments) is not None
        if is_glob and taken_over:
            user_sources = globs[0]
            continue
        canonical = _canonical(text)
        if (
            canonical in _TEMPLATE_STATEMENTS
            and not is_glob
            and (taken_over or not globs or canonical != _USER_SOURCES_TARGET)
        ):
            continue
        if statement.name == "if" and _is_debug_block(text):
            app_debug, kept_debug = _migrate_debug_block(text)
            if kept_debug:
                after.append(kept_debug)
            continue
        kept = content[statement.leading : statement.end].strip("\n")
        settings_side = library_at is None or index < library_at
        (before if settings_side else after).append(kept)
        where = "Project settings" if settings_side else "Kept"
        summary = f"{statement.name}({_canonical(statement.args)[:60]})"
        logging.info(
            tr(
                f"LibXR.CMake: kept {summary} of the earlier file in the {where} block",
                f"LibXR.CMake：已把旧文件中的 {summary} 保留在 {where} 块中",
            )
        )
    opt_debug = app_debug or toolchain_level(cmake_dir, "DEBUG") or ""
    opt_release = toolchain_level(cmake_dir, "RELEASE") or ""
    lines = ["set(LIBXR_SYSTEM None)", f"set(LIBXR_DRIVER {driver})"]
    if modules_dir:
        lines.append(f"set(XROBOT_MODULES_DIR {modules_dir})")
    lines += _setting_lines(opt_debug, opt_release, user_sources)
    settings = "\n".join(lines + before) + "\n"
    return settings, "\n\n".join(after)


def update_or_create_libxr_cmake(
    file_path: str, system: str, use_xrobot: bool, xrobot_modules_dir_line: str = ""
) -> None:
    """生成 LibXR.CMake，或把已有的文件重写为固定结构。
    Generate LibXR.CMake, or rewrite an existing file into the fixed structure.

    已有的新格式文件保留 “Project settings” 块（只校正 LIBXR_SYSTEM 和 XROBOT_MODULES_DIR，补上缺少
    的设置）和 “Kept” 块，其余块重新生成；旧格式的文件见 migrate_libxr_cmake()。新文件只在
    use_xrobot 为真时设置 XROBOT_MODULES_DIR，设置行用 xrobot_modules_dir_line（多核工程的核指向
    工程根目录的 Modules，见 integrate()），缺省时用 XROBOT_MODULES_DIR_LINE；已有的
    XROBOT_MODULES_DIR 不动。内容有变化时才写回。
    An existing file in the current format keeps its "Project settings" block (only LIBXR_SYSTEM
    and XROBOT_MODULES_DIR are corrected and missing settings added) and its "Kept" block, and
    the other blocks are generated again; a file in an earlier format is handled by
    migrate_libxr_cmake(). A new file sets XROBOT_MODULES_DIR only when use_xrobot is true, with
    xrobot_modules_dir_line as the setting line (the core of a multicore project names the
    Modules directory of the project root, see integrate()); without it XROBOT_MODULES_DIR_LINE
    is used. An existing XROBOT_MODULES_DIR stays. The file is written only when its content
    changes.
    """
    cmake_path = Path(file_path)
    if not cmake_path.exists():
        settings = default_settings(system, DEFAULT_OPT_DEBUG, DEFAULT_OPT_RELEASE)
        settings = (
            _follow_xrobot_choice(settings, use_xrobot, xrobot_modules_dir_line)
            if use_xrobot
            else settings
        )
        # XRobot 工程通过 LibXR 构建其 Modules；纯 LibXR 工程不得指定 Modules 目录。
        # XRobot projects build their Modules through LibXR; plain LibXR
        # projects must not name a Modules directory.
        cmake_path.write_text(render_libxr_cmake(settings), encoding="utf-8", newline="\n")
        logging.info(
            tr(f"Generated LibXR.CMake at: {cmake_path}", f"已生成 LibXR.CMake：{cmake_path}")
        )
        return

    content = read_text_with_fallback(str(cmake_path))
    blocks = split_blocks(content)
    if blocks is None:
        settings, kept = migrate_libxr_cmake(content, str(cmake_path.parent))
        logging.info(
            tr(
                "Migrated LibXR.CMake to the fixed structure with its project settings",
                "已把 LibXR.CMake 迁移到固定结构，工程设置保留",
            )
        )
    else:
        settings = blocks.get(SETTINGS_TITLE, "")
        kept = blocks.get(KEPT_TITLE, "")
    settings = _complete_settings(
        settings,
        system,
        use_xrobot,
        DEFAULT_OPT_DEBUG,
        DEFAULT_OPT_RELEASE,
        xrobot_modules_dir_line,
    )
    new_content = render_libxr_cmake(settings, kept)
    if new_content != content.replace("\r\n", "\n"):
        cmake_path.write_text(new_content, encoding="utf-8", newline="\n")
        # LIBXR_SYSTEM None 表示裸机，与生成代码时的“系统：裸机”一致。
        # LIBXR_SYSTEM None means bare metal, as in "System: bare metal" of the code generation.
        bare = system == "None"
        logging.info(
            tr(
                f"Updated existing LibXR.CMake for system: {'bare metal' if bare else system}",
                f"已更新现有的 LibXR.CMake，系统：{'裸机' if bare else system}",
            )
        )
    else:
        logging.info(
            tr(
                "LibXR.CMake already up to date, no changes needed.",
                "LibXR.CMake 已是最新，无需修改。",
            )
        )


# --------------------------
# 工具链文件 / Toolchain file
# --------------------------
# 旧版本插在 CubeMX 的 set(STARM_TOOLCHAIN_CONFIG "<默认>") 行之后的选择块。
# The selection block that earlier versions inserted after CubeMX's
# set(STARM_TOOLCHAIN_CONFIG "<default>") line.
STARM_PROFILE_SELECTION = """
# LibXR: -DSTARM_TOOLCHAIN_CONFIG=<profile> selects the profile of a build
# directory; a default changed by libxr stm32 toolchain also reaches
# existing build directories.
set(_xr_starm_default ${STARM_TOOLCHAIN_CONFIG})
unset(STARM_TOOLCHAIN_CONFIG)
if(NOT DEFINED CACHE{STARM_TOOLCHAIN_CONFIG} OR
   (DEFINED CACHE{XR_STARM_TOOLCHAIN_DEFAULT} AND
    NOT XR_STARM_TOOLCHAIN_DEFAULT STREQUAL _xr_starm_default))
  set(STARM_TOOLCHAIN_CONFIG ${_xr_starm_default} CACHE STRING "ST Arm Clang runtime profile" FORCE)
endif()
set(XR_STARM_TOOLCHAIN_DEFAULT ${_xr_starm_default} CACHE INTERNAL "Default STARM_TOOLCHAIN_CONFIG of this file")
set_property(CACHE STARM_TOOLCHAIN_CONFIG PROPERTY STRINGS STARM_HYBRID STARM_NEWLIB STARM_PICOLIBC)"""
# 旧版本在计算 multilib 参数的 if 块之前加入的初始化，以及块中的未知配置名检查。
# The initialization that earlier versions added before the if block computing the multilib
# flags, and the check for an unknown profile name inside the block.
_STARM_MULTILIBS_INIT = (
    'set(TOOLCHAIN_MULTILIBS "")\n\nif(STARM_TOOLCHAIN_CONFIG STREQUAL "STARM_HYBRID")'
)
_STARM_UNKNOWN_PROFILE = (
    'elseif(NOT STARM_TOOLCHAIN_CONFIG STREQUAL "STARM_PICOLIBC")\n'
    '  message(FATAL_ERROR "Unknown STARM_TOOLCHAIN_CONFIG: ${STARM_TOOLCHAIN_CONFIG}")\n'
)
# 更早的版本把默认行改成 CACHE STRING，并在之后加一条属性列表。
# Still earlier versions turned the default line into a CACHE STRING and added a property list
# after it.
_STARM_CACHE_LINE = re.compile(
    r'(set\s*\(\s*STARM_TOOLCHAIN_CONFIG\s+"[^"]+")\s+CACHE\s+STRING\s+"[^"]*"(\s*\))'
    r"(?:[ \t]*\n[ \t]*set_property\s*\(\s*CACHE\s+STARM_TOOLCHAIN_CONFIG\s+PROPERTY\s+STRINGS"
    r"\s+STARM_HYBRID\s+STARM_NEWLIB\s+STARM_PICOLIBC\s*\))?"
)


def restore_starm_clang_toolchain(file_path: str | Path) -> bool:
    """去掉旧版本加进 cmake/starm-clang.cmake 的内容，恢复 CubeMX 写出的原文；写回时返回 True。
    Remove what earlier versions added to cmake/starm-clang.cmake and restore the text CubeMX
    wrote; True when the file was written back.

    去掉的有三处：默认行之后的选择块（或更早的 CACHE STRING 写法）、multilib if 块之前的
    set(TOOLCHAIN_MULTILIBS "") 和块中对未知配置名的检查。只有这些内容原样出现时才去掉，用户自己
    的修改不动。文件不存在或没有这些内容时什么也不做；换行符保持文件原来的写法。
    Three things go: the selection block after the default line (or the still earlier CACHE
    STRING form), the set(TOOLCHAIN_MULTILIBS "") before the multilib if block, and the check
    for an unknown profile inside the block. They are removed only where they appear as written;
    the user's own edits stay. A missing file, or one without them, is left alone, and the line
    endings stay as the file has them.
    """
    path = Path(file_path)
    if not path.exists():
        return False
    raw = path.read_bytes()
    eol = "\r\n" if b"\r\n" in raw else "\n"
    content = raw.decode("utf-8").replace("\r\n", "\n")
    restored = content.replace(STARM_PROFILE_SELECTION, "", 1)
    restored = _STARM_CACHE_LINE.sub(r"\1\2", restored, count=1)
    restored = restored.replace(
        _STARM_MULTILIBS_INIT, 'if(STARM_TOOLCHAIN_CONFIG STREQUAL "STARM_HYBRID")', 1
    )
    restored = restored.replace(_STARM_UNKNOWN_PROFILE, "", 1)
    if restored == content:
        return False
    path.write_bytes(restored.replace("\n", eol).encode("utf-8"))
    logging.info(
        tr(
            f"Restored {path} to what CubeMX wrote",
            f"已把 {path} 恢复为 CubeMX 写出的原文",
        )
    )
    return True


def integrate(input_directory: str) -> None:
    """把 LibXR 接入 input_directory 中的 CubeMX CMake 工程。
    Integrate LibXR into the CubeMX CMake project in input_directory.

    依次生成或重写 cmake/LibXR.CMake，把 cmake/starm-clang.cmake 恢复为 CubeMX 原样，并在
    CMakeLists.txt 没有 include LibXR.CMake 时（见 includes_libxr_cmake()）写进 include 块（见
    update_cmake_include()）。LIBXR_SYSTEM 由 Core/Inc 中的 FreeRTOSConfig.h 或 app_threadx.h
    决定，都没有时为 None。input_directory 自己没有 Middlewares/Third_Party/LibXR 而父目录有
    （多核工程的一个核，见 project_root_for()）时，CMakeLists.txt 中的 LIBXR_SOURCE_DIR 指向父
    目录里的子模块。输入目录或 CMakeLists.txt 不存在时以状态 1 退出。
    In order, it generates or rewrites cmake/LibXR.CMake, restores cmake/starm-clang.cmake to
    what CubeMX wrote, and writes the block that includes LibXR.CMake into CMakeLists.txt when
    it does not include it yet (see includes_libxr_cmake() and update_cmake_include()).
    LIBXR_SYSTEM follows FreeRTOSConfig.h or app_threadx.h in Core/Inc, and is None without
    either. When input_directory has no Middlewares/Third_Party/LibXR of its own while its
    parent does (a core of a multicore project, see project_root_for()), the LIBXR_SOURCE_DIR
    in CMakeLists.txt names the submodule in the parent. A missing input directory or
    CMakeLists.txt exits with status 1.
    """

    if not os.path.isdir(input_directory):
        logging.error(
            tr(f"Directory does not exist: {input_directory}", f"目录不存在：{input_directory}")
        )
        sys.exit(1)
    main_cmake_path = os.path.join(input_directory, "CMakeLists.txt")
    # 先检查 CMakeLists.txt，再写文件。
    # Check CMakeLists.txt before writing anything.
    if not os.path.exists(main_cmake_path):
        logging.error(tr(f"{main_cmake_path} not found.", f"找不到 {main_cmake_path}。"))
        sys.exit(1)

    project_root = project_root_for(input_directory)

    cmake_dir = os.path.join(input_directory, "cmake")
    os.makedirs(cmake_dir, exist_ok=True)

    file_path = os.path.join(cmake_dir, "LibXR.CMake")

    freertos_enable = os.path.exists(
        os.path.join(input_directory, "Core", "Inc", "FreeRTOSConfig.h")
    )
    threadx_enable = os.path.exists(os.path.join(input_directory, "Core", "Inc", "app_threadx.h"))

    if freertos_enable:
        system = "FreeRTOS"
    elif threadx_enable:
        system = "ThreadX"
    else:
        system = "None"

    # 多核工程的 XRobot Modules 常在工程根目录；核自己没有 Modules 而根目录有时，设置行指向根
    # 目录的 Modules。LibXR.CMake 被 include 时 CMAKE_CURRENT_SOURCE_DIR 仍是核的目录，而
    # CMAKE_CURRENT_LIST_DIR 已是 cmake/ 子目录，所以这里用 SOURCE_DIR。
    # The XRobot Modules of a multicore project usually sit in the project root; when the core
    # has none of its own while the root does, the setting line names the root's Modules. While
    # LibXR.CMake is included, CMAKE_CURRENT_SOURCE_DIR still names the core's directory while
    # CMAKE_CURRENT_LIST_DIR already names its cmake/ subdirectory, so SOURCE_DIR is used here.
    use_xrobot = project_uses_xrobot(input_directory)
    xrobot_modules_dir_line = ""
    if use_xrobot and project_root != os.path.abspath(input_directory):
        prefix = _root_prefix(input_directory, project_root)
        if not os.path.isdir(os.path.join(input_directory, "Modules")) and os.path.isdir(
            os.path.join(project_root, "Modules")
        ):
            xrobot_modules_dir_line = (
                f'set(XROBOT_MODULES_DIR "${{CMAKE_CURRENT_SOURCE_DIR}}/{prefix}Modules")'
            )

    update_or_create_libxr_cmake(file_path, system, use_xrobot, xrobot_modules_dir_line)

    restore_starm_clang_toolchain(os.path.join(cmake_dir, "starm-clang.cmake"))

    update_cmake_include(input_directory, project_root)


# 非注释的 “# Add LibXR” 块：可选的 LIBXR_SYSTEM 行（5.x 的 xr_stm32_cmake 写的）和
# LIBXR_SOURCE_DIR 行加上 include 行。
# The uncommented "# Add LibXR" block: an optional LIBXR_SYSTEM line (written by the xr_stm32_cmake
# of 5.x) and an optional LIBXR_SOURCE_DIR line plus the include line.
_LIBXR_INCLUDE_BLOCK = re.compile(
    r"(?ms)^"
    r"(?:# Add LibXR[ \t]*\n)?"
    r"(?:set\(LIBXR_SYSTEM[^\n]*\)[ \t]*\n)?"
    r"(?:set\(LIBXR_SOURCE_DIR[^\n]*\)[ \t]*\n)?"
    r"include\(\$\{CMAKE_CURRENT_LIST_DIR\}/(?:\.\./)?cmake/LibXR\.CMake\)[ \t]*\n?"
)


def project_root_for(input_directory: str) -> str:
    """持有 LibXR 子模块的工程根目录：input_directory 自带 Middlewares/Third_Party/LibXR 时是
    它自己，父目录带时是父目录，否则仍是它自己（找不到子模块时不改变行为）。
    The project root holding the LibXR submodule: input_directory itself when it contains
    Middlewares/Third_Party/LibXR, its parent when the parent does, and input_directory again
    when neither does (a missing submodule changes nothing).

    多核工程的 LibXR 子模块只加入工程根目录一次，每个核的子工程通过 LIBXR_SOURCE_DIR 用它。
    A multicore project adds the LibXR submodule to its root once, and every core's subproject
    uses it through LIBXR_SOURCE_DIR.
    """
    directory = os.path.abspath(input_directory)
    if os.path.isdir(os.path.join(directory, "Middlewares", "Third_Party", "LibXR")):
        return directory
    parent = os.path.dirname(directory)
    if os.path.isdir(os.path.join(parent, "Middlewares", "Third_Party", "LibXR")):
        return parent
    return directory


def _root_prefix(input_directory: str, project_root: str) -> str:
    """从 input_directory 到工程根目录 project_root 的相对路径前缀，带一个斜杠（同一目录时为空）。
    The relative path prefix from input_directory to the project root project_root, with one
    slash (empty when both are the same directory).
    """
    relative_root = os.path.relpath(project_root, input_directory).replace(os.sep, "/")
    return "" if relative_root == "." else f"{relative_root}/"


def cmake_include_block(input_directory: str, project_root: str) -> str:
    """多核工程的一个核写进 CMakeLists.txt 的块：把 LIBXR_SOURCE_DIR 指到工程根目录里的子模块，
    再 include 本核自己的 LibXR.CMake（其中的设置属于这一个核）。
    The block a core of a multicore project writes into its CMakeLists.txt: LIBXR_SOURCE_DIR
    names the submodule in the project root, then the core's own LibXR.CMake is included (its
    settings belong to this one core).
    """
    prefix = _root_prefix(input_directory, project_root)
    return (
        "set(LIBXR_SOURCE_DIR "
        f'"${{CMAKE_CURRENT_LIST_DIR}}/{prefix}Middlewares/Third_Party/LibXR")\n'
        "include(${CMAKE_CURRENT_LIST_DIR}/cmake/LibXR.CMake)\n"
    )


def update_cmake_include(input_directory: str, project_root: str) -> None:
    """把 include LibXR.CMake 的块写进 input_directory 的 CMakeLists.txt。
    Write the block that includes LibXR.CMake into the CMakeLists.txt of input_directory.

    单核工程（project_root 就是 input_directory）保持 6.0.0 的行为：没有 include 时追加一行。
    多核工程的一个核没有 include 块时追加 LIBXR_SOURCE_DIR 行和 include；已有块（5.x 写的带
    LIBXR_SYSTEM 的、只写了 include 的，或上一次运行写出的）时原位更新；已有自定义写法的
    include（不是本模块写的块）时保留原样，不追加第二个 include。LIBXR_SOURCE_DIR 让这个核把
    工程根目录里的 LibXR 子模块（而不是它自己没有的 Middlewares）加进构建；CMake 3.21 起的默认
    策略下普通变量会遮蔽 LibXR.CMake 里的 CACHE PATH 默认值。
    A single-core project (project_root is input_directory) keeps the 6.0.0 behavior: one line
    is appended when the include is missing. A core of a multicore project without an include
    block gains a LIBXR_SOURCE_DIR line and the include; an existing block (the 5.x one with a
    LIBXR_SYSTEM line, one with only the include, or one written by a previous run) is updated
    in place; a custom include this module did not write is left alone instead of gaining a
    second one. LIBXR_SOURCE_DIR makes the core add the LibXR submodule of the project root to
    the build, not the Middlewares it does not have itself; with the default policy of CMake
    3.21 and later the normal variable shadows the CACHE PATH default inside LibXR.CMake.
    """
    main_cmake_path = os.path.join(input_directory, "CMakeLists.txt")
    if project_root == os.path.abspath(input_directory):
        # 单核：与 6.0.0 相同，只在没有 include 时追加。
        # Single core: as in 6.0.0, append only when the include is missing.
        if not os.path.exists(main_cmake_path):
            logging.error(tr(f"{main_cmake_path} not found.", f"找不到 {main_cmake_path}。"))
            sys.exit(1)
        if not includes_libxr_cmake(read_text_with_fallback(main_cmake_path)):
            with open(main_cmake_path, "a", encoding="utf-8", newline="\n") as f:
                f.write("\n# Add LibXR\n" + include_cmake_cmd)
            logging.info(
                tr(
                    "LibXR.CMake included in CMakeLists.txt.",
                    "已在 CMakeLists.txt 中 include LibXR.CMake。",
                )
            )
        else:
            logging.info(
                tr(
                    "LibXR.CMake already included in CMakeLists.txt.",
                    "CMakeLists.txt 已经 include LibXR.CMake。",
                )
            )
        return

    if not os.path.exists(main_cmake_path):
        logging.error(tr(f"{main_cmake_path} not found.", f"找不到 {main_cmake_path}。"))
        sys.exit(1)
    content = read_text_with_fallback(main_cmake_path)
    if _LIBXR_INCLUDE_BLOCK.search(content):
        # 已有块：原位替换，块之外的行（如用户自己的 target_compile_definitions）不动。
        # An existing block: replace it in place; lines outside it, such as the user's own
        # target_compile_definitions, stay.
        block = "# Add LibXR\n" + cmake_include_block(input_directory, project_root)
        new_content = _LIBXR_INCLUDE_BLOCK.sub(block, content, count=1)
        updated = True
    elif includes_libxr_cmake(content):
        logging.info(
            tr(
                "CMakeLists.txt already includes LibXR.CMake with a custom block; left as is.",
                "CMakeLists.txt 已用自定义的块 include LibXR.CMake；保持原样。",
            )
        )
        return
    else:
        block = "# Add LibXR\n" + cmake_include_block(input_directory, project_root)
        new_content = content.rstrip() + "\n\n" + block
        updated = False
    if new_content != content:
        with open(main_cmake_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(new_content)
        if updated:
            logging.info(
                tr(
                    "LibXR.CMake include updated in CMakeLists.txt.",
                    "已更新 CMakeLists.txt 中的 LibXR.CMake include。",
                )
            )
        else:
            logging.info(
                tr(
                    "LibXR.CMake included in CMakeLists.txt.",
                    "已在 CMakeLists.txt 中 include LibXR.CMake。",
                )
            )
    else:
        logging.info(
            tr(
                "LibXR.CMake already included in CMakeLists.txt.",
                "CMakeLists.txt 已经 include LibXR.CMake。",
            )
        )


if __name__ == "__main__":
    from libxr.legacy import run

    raise SystemExit(run("xr_stm32_cmake"))
