"""libxr parse 对 MSPM0 工程：解析 SysConfig 工程并写出工程 YAML。
libxr parse for an MSPM0 project: parse the SysConfig project and write the project YAML.

工程是根目录中唯一的 .syscfg。解析读两个来源：.syscfg 本身（外设实例、参数和引脚分配），以及
SysConfig 生成的 ti_msp_dl_config.h/.c（实际生成的宏名、CPUCLK_FREQ、ULPCLK 分频和各实例的时钟
配置）。设置了 SYSCONFIG_TOOL 和 MSPM0_SDK_INSTALL_DIR（与 CMake 的 MSPM0SysConfig.cmake 用的环境
变量相同）时总是运行一次 SysConfig，生成到临时目录；没有设置时复用工程目录 build*、cmake-build*
或 out 下比 .syscfg 新的生成结果。复用只比较修改时间：换成一个修改时间更旧的 .syscfg 时，旧输出
仍会被复用，这时请重新构建或设置这两个变量。
The project is the single .syscfg in the root. Parsing reads two sources: the .syscfg itself
(peripheral instances, parameters and pin assignments) and the ti_msp_dl_config.h/.c that
SysConfig generates (the macro names actually emitted, CPUCLK_FREQ, the ULPCLK divider and the
clock configuration of each instance). With SYSCONFIG_TOOL and MSPM0_SDK_INSTALL_DIR set (the
environment variables the CMake MSPM0SysConfig.cmake uses as well) SysConfig always runs once,
into a temporary directory; without them a generated output newer than the .syscfg under
build*, cmake-build* or out in the project is reused. Reuse compares modification times only: a
.syscfg replaced by one with an older modification time still reuses the old output, so build
again or set the two variables then.

外设分两类：LibXR 有驱动的（UART、控制器模式的 I2C 和 SPI、PWM）进入 Peripherals，gen 为它们
生成对象；其余（ADC12、DAC12、MCAN、QEI、目标模式的 I2C、外设模式的 SPI……）记入 Other，只作
展示。GPIO 引脚进入 GPIO 段。
Peripherals split in two: the ones LibXR has drivers for (UART, I2C and SPI in controller mode,
PWM) go into Peripherals and gen generates objects for them; the rest (ADC12, DAC12, MCAN, QEI,
an I2C in target mode, an SPI in peripheral mode, ...) are recorded under Other for display
only. The GPIO pins go into the GPIO section.
"""

from __future__ import annotations

import logging
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml
from xr_syntax.i18n import tr

from libxr import pin_layout, pin_project
from libxr.generator_code_stm32 import CPP_KEYWORDS


def _save_to_yaml(data: dict, output_path: str) -> bool:
    """把工程数据写成 YAML，首行为 SysConfig 工程的生成文件说明；成功时为 True。
    Write the project data as YAML with a generated-file notice for a SysConfig project on the
    first line; True on success.
    """
    try:
        directory = os.path.dirname(output_path)
        if directory:
            os.makedirs(directory, exist_ok=True)
        with open(output_path, "w", encoding="utf-8", newline="\n") as file:
            file.write(
                "# Generated by `libxr parse` from the SysConfig project file; "
                "do not edit by hand.\n"
            )
            yaml.dump(
                data, file, allow_unicode=True, sort_keys=False, default_flow_style=False, indent=2
            )
        logging.info(
            tr(f"Configuration exported to: {output_path}", f"配置已导出到：{output_path}")
        )
        return True
    except (OSError, yaml.YAMLError) as error:
        logging.error(tr(f"YAML export failed: {str(error)}", f"YAML 导出失败：{str(error)}"))
        return False


def _print_summary(data: dict) -> None:
    """向标准输出打印配置摘要：器件、GPIO 引脚和各类外设实例。
    Print a configuration summary to standard output: the device, the GPIO pins and the
    peripheral instances of each kind.
    """
    print(tr("\n===== [Configuration Summary] =====", "\n===== [配置摘要] ====="))
    mcu = data.get("Mcu", {})
    print(
        tr(
            f"\nMCU: {mcu.get('Family', '')} {mcu.get('Type', '')}",
            f"\nMCU：{mcu.get('Family', '')} {mcu.get('Type', '')}",
        )
    )
    gpio = data.get("GPIO", {})
    print(tr(f"\nGPIO ({len(gpio)} pins):", f"\nGPIO（{len(gpio)} 个引脚）："))
    for label, pin in gpio.items():
        direction = pin["Direction"]
        if "Interrupt" in pin:
            print(
                tr(
                    f"  {label}: {pin['Pin']}, {direction}, {pin['Interrupt']} interrupt",
                    f"  {label}：{pin['Pin']}，{direction}，{pin['Interrupt']} 中断",
                )
            )
        else:
            print(
                tr(f"  {label}: {pin['Pin']}, {direction}", f"  {label}：{pin['Pin']}，{direction}")
            )
    print(tr("\nActive Peripherals:", "\n已启用的外设："))
    for section, group in data.get("Peripherals", {}).items():
        print(tr(f"  {section}: {len(group)} instance(s)", f"  {section}：{len(group)} 个实例"))
        for name in group:
            print(f"    {name}")


# SysConfig 运行的时限（秒）。
# Time limit in seconds for a SysConfig run.
SYSCONFIG_TIMEOUT = 300

# 复用 SysConfig 输出时找的构建目录（工程根目录下的 glob）。
# The build directories searched for a SysConfig output to reuse (globs in the project root).
BUILD_DIRECTORIES = ("build*", "cmake-build*", "out")

# LibXR 有驱动、gen 生成对象的模块：模块名 -> Peripherals 段的键。
# The modules LibXR has drivers for and gen generates objects for: module -> the key of the
# Peripherals section.
GENERATED_MODULES = {"UART": "UART", "I2C": "I2C", "SPI": "SPI", "PWM": "PWM"}

SYSCFG_GPIO_PARAM = re.compile(r"^\.associatedPins\[(\d+)\]\.(\w+)$")
SYSCFG_PERIPH_MEMBER = re.compile(r"^\.peripheral\.(\w+)\.\$(assign|suggestSolution)$")
SYSCFG_PWM_CHANNEL = re.compile(r"^ccp(\d+)Pin$")
# 实例的时钟配置结构：gI2C_0ClockConfig，SPI 写成 gSPI_1_clockConfig；成员按列对齐，等号前的
# 空格数不定。
# The clock configuration struct of an instance: gI2C_0ClockConfig, written gSPI_1_clockConfig
# for an SPI; the members are aligned in columns, so the spaces before the equals sign vary.
CLOCK_CONFIG = re.compile(r"static const \w+ g(\w+?)_?[Cc]lockConfig\s*=\s*\{(.*?)\};", re.S)
CLOCK_MEMBER = r"\.{}\s*=\s*(\w+)"
HEADER_DEFINE = re.compile(r"^#define[ \t]+(\w+)(?:[ \t]+(.*?))?[ \t\r]*$", re.M)
DMA_TRIGGER = re.compile(r"\(?\s*DMA_\w+?_(TX|RX)_TRIG\s*\)?")
IDENTIFIER = re.compile(r"[A-Za-z_]\w*")


def _strip_comments(text: str) -> str:
    """.syscfg 的正文：去掉块注释和行注释。
    The body of a .syscfg: block comments and line comments removed.
    """
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"^[ \t]*//.*$", "", text, flags=re.M)


class Instances:
    """一个 .syscfg 的全部实例：变量 -> 模块、名字、外设、参数、引脚成员和 DMA 子实例。
    Every instance of one .syscfg: variable -> module, name, peripheral, parameters, pin
    members and DMA sub-instances.
    """

    def __init__(self, text: str) -> None:
        """解析 .syscfg 的脚本正文，按变量记下每个实例的全部赋值。外设和引脚都是 $assign 优先，
        求解器的 $suggestSolution 兜底（与 libxr pins 的读法相同）。
        Parse the script body of a .syscfg and record every assignment of each instance by its
        variable. For the peripheral and the pins $assign wins and the solver's
        $suggestSolution is the fallback, as libxr pins reads them.
        """
        text = _strip_comments(text)
        modules = dict(pin_project.SYSCFG_MODULE.findall(text))
        instances = dict(modules)
        instances.update(
            {
                var: modules[module]
                for var, module in pin_project.SYSCFG_INSTANCE.findall(text)
                if module in modules
            }
        )
        self.of_var: dict[str, dict] = {}
        for var, tail, value in pin_project.SYSCFG_ASSIGNMENT.findall(text):
            if var not in instances:
                continue
            entry = self.of_var.setdefault(
                var,
                {
                    "module": instances[var],
                    "name": None,
                    "peripheral": None,
                    "params": {},
                    "pins": {},
                    "dma": {},
                    "gpio": {},
                },
            )
            value = pin_project.syscfg_value(value)
            if tail == ".$name":
                entry["name"] = value
            elif tail == ".peripheral.$assign":
                entry["peripheral"] = value
            elif tail == ".peripheral.$suggestSolution":
                entry["peripheral"] = entry["peripheral"] or value
            elif tail.startswith(".peripheral."):
                member = SYSCFG_PERIPH_MEMBER.match(tail)
                # $assign 覆盖同名成员的 $suggestSolution，反过来不覆盖。
                # $assign overrides a $suggestSolution of the same member, not the other way.
                if member and (member.group(2) == "assign" or member.group(1) not in entry["pins"]):
                    entry["pins"][member.group(1)] = value
            elif tail.startswith(".DMA_CHANNEL_"):
                entry["dma"][tail] = value
            elif tail.startswith(".associatedPins["):
                index = int(re.match(r"^\.associatedPins\[(\d+)\]", tail).group(1))
                pin = entry["gpio"].setdefault(index, {})
                if tail == f".associatedPins[{index}].$name":
                    pin["name"] = value
                elif tail in (
                    f".associatedPins[{index}].pin.$assign",
                    f".associatedPins[{index}].pin.$suggestSolution",
                ):
                    if tail.endswith(".$assign") or "pin" not in pin:
                        pin["pin"] = value
                else:
                    param = SYSCFG_GPIO_PARAM.match(tail)
                    if param and not param.group(2).startswith("$"):
                        pin[param.group(2)] = value
            elif "$" not in tail:
                entry["params"][tail.lstrip(".")] = value

    def peripherals(self, module: str) -> dict[str, dict]:
        """模块 module 的实例，按 .syscfg 中的出现顺序，实例名 -> 数据；没有名字的实例跳过。
        The instances of module, in .syscfg order, instance name -> its data; an instance
        without a name is skipped.
        """
        found = {}
        for entry in self.of_var.values():
            if entry["module"] == module and entry["name"]:
                found[entry["name"]] = entry
        return found


def _fail(message: str):
    """记录错误并以状态 1 退出。
    Log an error and exit with status 1.
    """
    logging.error(message)
    sys.exit(1)


def _read_output(directory: Path) -> tuple[str, str]:
    """directory 中 ti_msp_dl_config.h 和 .c 的内容。
    The contents of ti_msp_dl_config.h and .c in directory.
    """
    header = directory / "ti_msp_dl_config.h"
    source = directory / "ti_msp_dl_config.c"
    return header.read_text(encoding="utf-8", errors="replace"), source.read_text(
        encoding="utf-8", errors="replace"
    )


def _sysconfig_problems(tool: str, sdk: str) -> list[tuple[str, str]]:
    """SysConfig 环境的问题：没有设置的变量，或设置了但指错的路径；没有问题时为空。
    The problems of the SysConfig environment: a variable that is not set, or one that is set
    to a wrong path; empty when there is none.
    """
    problems = []
    if not tool:
        problems.append(("SYSCONFIG_TOOL is not set", "没有设置 SYSCONFIG_TOOL"))
    elif not os.path.isfile(tool):
        problems.append(
            (
                f"SYSCONFIG_TOOL={tool} is not a file (it names sysconfig_cli.bat or "
                "sysconfig_cli.sh)",
                f"SYSCONFIG_TOOL={tool} 不是文件（应指向 sysconfig_cli.bat 或 sysconfig_cli.sh）",
            )
        )
    if not sdk:
        problems.append(("MSPM0_SDK_INSTALL_DIR is not set", "没有设置 MSPM0_SDK_INSTALL_DIR"))
    elif not os.path.isfile(os.path.join(sdk, ".metadata", "product.json")):
        problems.append(
            (
                f"MSPM0_SDK_INSTALL_DIR={sdk} has no .metadata/product.json",
                f"MSPM0_SDK_INSTALL_DIR={sdk} 中没有 .metadata/product.json",
            )
        )
    return problems


def _reusable_output(directory: Path, syscfg: Path) -> Path | None:
    """工程构建目录（BUILD_DIRECTORIES）中比 .syscfg 新、.h 和 .c 都在的最新一份 SysConfig 输出
    目录；没有时为 None。
    The newest SysConfig output directory in the build directories of the project
    (BUILD_DIRECTORIES) that is newer than the .syscfg and holds both the .h and the .c; None
    when there is none.
    """
    syscfg_mtime = syscfg.stat().st_mtime
    headers = [
        path
        for pattern in BUILD_DIRECTORIES
        for path in directory.glob(f"{pattern}/**/syscfg/ti_msp_dl_config.h")
        if path.stat().st_mtime >= syscfg_mtime and path.with_suffix(".c").is_file()
    ]
    if not headers:
        return None
    return max(headers, key=lambda path: path.stat().st_mtime).parent


def _sysconfig_output(directory: Path, syscfg: Path) -> tuple[str, str]:
    """SysConfig 生成的 ti_msp_dl_config.h 和 .c 的内容：SysConfig 环境可用时运行它到临时目录
    （用后删除），否则复用构建目录中比 .syscfg 新的输出；都不行时说明缺什么并退出。
    The contents of the ti_msp_dl_config.h/.c SysConfig generates: with a usable SysConfig
    environment it runs into a temporary directory (removed afterwards), otherwise an output in
    a build directory that is newer than the .syscfg is reused; when neither works, say what is
    missing and exit.
    """
    tool = os.environ.get("SYSCONFIG_TOOL", "")
    sdk = os.environ.get("MSPM0_SDK_INSTALL_DIR", "")
    problems = _sysconfig_problems(tool, sdk)
    if not problems:
        return _run_sysconfig(tool, sdk, syscfg)
    english = "; ".join(problem[0] for problem in problems)
    chinese = "；".join(problem[1] for problem in problems)

    reused = _reusable_output(directory, syscfg)
    if reused is not None and (tool or sdk):
        # 设置了却指错的环境变量要说出来，否则用户不知道 SysConfig 为什么没有运行。
        # A variable that is set but wrong is reported; otherwise nobody learns why SysConfig
        # did not run.
        logging.warning(
            tr(
                f"SysConfig cannot run: {english}; the build output is reused instead",
                f"无法运行 SysConfig：{chinese}；改为复用构建输出",
            )
        )
    if reused is not None:
        build_dir = reused.parent
        label = (
            build_dir.relative_to(directory) if build_dir.is_relative_to(directory) else build_dir
        )
        logging.info(
            tr(f"Reusing the SysConfig output in {label}", f"复用 {label} 中的 SysConfig 输出")
        )
        return _read_output(reused)

    _fail(
        tr(
            f"{directory}: no SysConfig output newer than {syscfg.name} found under "
            f"{', '.join(BUILD_DIRECTORIES)}, and SysConfig cannot run: {english} (the "
            "environment variables the CMake build uses). Build the project once, or set them "
            "and run `libxr parse` again.",
            f"{directory}：{'、'.join(BUILD_DIRECTORIES)} 下没有比 {syscfg.name} 新的 SysConfig "
            f"输出，且无法运行 SysConfig：{chinese}（CMake 构建使用的环境变量）。请先构建一次"
            "工程，或设置它们后重新运行 `libxr parse`。",
        )
    )


def _run_sysconfig(tool: str, sdk: str, syscfg: Path) -> tuple[str, str]:
    """用 SysConfig 生成 syscfg 的输出到临时目录并读出 .h 和 .c；运行失败、超时或无法启动时
    记录错误并退出。
    Generate the output of syscfg into a temporary directory with SysConfig and read the .h and
    the .c; a failed, timed-out or unstartable run logs an error and exits.
    """
    output = tempfile.mkdtemp(prefix="libxr-sysconfig-")
    try:
        command = [
            tool,
            "--compiler",
            "gcc",
            "--product",
            os.path.join(sdk, ".metadata", "product.json"),
            "--output",
            output,
            str(syscfg),
        ]
        logging.info(
            tr(f"Running SysConfig on {syscfg.name}", f"正在对 {syscfg.name} 运行 SysConfig")
        )
        try:
            result = subprocess.run(
                command, capture_output=True, text=True, timeout=SYSCONFIG_TIMEOUT
            )
        except subprocess.TimeoutExpired:
            _fail(
                tr(
                    f"SysConfig did not finish on {syscfg} within {SYSCONFIG_TIMEOUT} s ({tool})",
                    f"SysConfig 在 {SYSCONFIG_TIMEOUT} 秒内没有处理完 {syscfg}（{tool}）",
                )
            )
        except OSError as error:
            _fail(
                tr(
                    f"Cannot run SysConfig ({tool}): {error}",
                    f"无法运行 SysConfig（{tool}）：{error}",
                )
            )
        if result.returncode != 0:
            _fail(
                tr(
                    f"SysConfig failed on {syscfg}:\n{result.stdout}{result.stderr}",
                    f"SysConfig 在 {syscfg} 上运行失败：\n{result.stdout}{result.stderr}",
                )
            )
        try:
            return _read_output(Path(output))
        except OSError as error:
            _fail(
                tr(
                    f"SysConfig wrote no ti_msp_dl_config.h/.c for {syscfg}: {error}",
                    f"SysConfig 没有为 {syscfg} 写出 ti_msp_dl_config.h/.c：{error}",
                )
            )
    finally:
        shutil.rmtree(output, ignore_errors=True)


def _header_defines(header: str) -> dict[str, str]:
    """ti_msp_dl_config.h 定义的宏，按出现顺序：宏名 -> 值（去掉首尾空白，没有值时为空串）。
    The macros ti_msp_dl_config.h defines, in order: name -> value (stripped, empty when the
    macro has none).
    """
    return {name: (value or "").strip() for name, value in HEADER_DEFINE.findall(header)}


def _cpuclk(defines: dict[str, str]) -> int | None:
    """ti_msp_dl_config.h 里的 CPUCLK_FREQ；没有时为 None。
    The CPUCLK_FREQ of ti_msp_dl_config.h; None when it does not define one.
    """
    match = re.fullmatch(r"\(?(\d+)U?\)?", defines.get("CPUCLK_FREQ", ""))
    return int(match.group(1)) if match else None


def _ulpclk_divider(source: str) -> int:
    """ti_msp_dl_config.c 里 DL_SYSCTL_setULPCLKDivider 的分频数；没有调用时为 1。
    The divider of DL_SYSCTL_setULPCLKDivider in ti_msp_dl_config.c; 1 without a call.
    """
    match = re.search(r"DL_SYSCTL_setULPCLKDivider\s*\(\s*DL_SYSCTL_ULPCLK_DIV_(\d+)", source)
    return int(match.group(1)) if match else 1


def _clock_configs(source: str) -> dict[str, dict]:
    """ti_msp_dl_config.c 里每个实例的时钟配置：实例名（I2C_0、SPI_1）-> clockSel 和
    divideRatio。
    The clock configuration of every instance in ti_msp_dl_config.c: instance name (I2C_0,
    SPI_1) -> its clockSel and divideRatio.
    """
    found: dict[str, dict] = {}
    for name, body in CLOCK_CONFIG.findall(source):
        sel = re.search(CLOCK_MEMBER.format("clockSel"), body)
        div = re.search(CLOCK_MEMBER.format("divideRatio"), body)
        found[name] = {
            "clockSel": sel.group(1) if sel else None,
            "divideRatio": div.group(1) if div else None,
        }
    return found


def _clock_is_default(clock: dict) -> bool:
    """实例的 SysConfig 时钟配置是否为默认的 BUSCLK + 分频 1（驱动会重设时钟的外设，例如 I2C，
    这只描述 SysConfig 写下的初值）。
    Whether the SysConfig clock configuration of the instance is the default BUSCLK with divider
    1; for a peripheral whose driver resets the clock, such as an I2C, this only describes the
    initial value SysConfig wrote.
    """
    sel, div = clock.get("clockSel"), clock.get("divideRatio")
    return sel in (
        None,
        "DL_I2C_CLOCK_BUSCLK",
        "DL_SPI_CLOCK_BUSCLK",
        "DL_TIMER_CLOCK_BUSCLK",
        "DL_UART_MAIN_CLOCK_BUSCLK",
    ) and div in (
        None,
        "DL_I2C_CLOCK_DIVIDE_1",
        "DL_SPI_CLOCK_DIVIDE_RATIO_1",
        "DL_TIMER_CLOCK_DIVIDE_1",
        "DL_UART_MAIN_CLOCK_DIVIDE_RATIO_1",
    )


def _device_names(power_domains: dict[str, int], defines: dict[str, str]) -> set[str]:
    """GPIO 对象名不能用的器件名字：器件头文件的外设实例宏（UART0、SPI1、TIMG0、GPIOA……，取自
    P1 数据的电源域表）和 ti_msp_dl_config.h 定义的宏。
    The device names a GPIO object cannot take: the peripheral instance macros of the device
    header (UART0, SPI1, TIMG0, GPIOA, ..., from the power domain table of the P1 data) and the
    macros ti_msp_dl_config.h defines.
    """
    names = {name for name in power_domains if not re.fullmatch(r"P[A-Z]\d+", name)}
    names.update({"GPIOA", "GPIOB", "GPIOC"})
    names.update(defines)
    return names


def _gpio_label(syscfg: Path, group: str, name: str) -> str:
    """GPIO 对象名：引脚 $name 去掉 PIN_ 前缀（PIN_LED1 -> LED1）；去掉后不是合法标识符时
    （SysConfig 的默认名 PIN_0 -> 0）退回小写的组名加引脚名（gpio_btn_pin_0），并提示怎样在
    SysConfig 中改名。
    The GPIO object name: the pin $name without its PIN_ prefix (PIN_LED1 -> LED1); when that
    is not a valid identifier (the SysConfig default PIN_0 -> 0) it falls back to the
    lower-case group plus pin name (gpio_btn_pin_0), with a hint on renaming in SysConfig.
    """
    label = name[4:] if name.startswith("PIN_") else name
    if IDENTIFIER.fullmatch(label):
        return label
    fallback = re.sub(r"\W", "_", f"{group}_{name}".lower())
    logging.warning(
        tr(
            f"{syscfg.name}: the GPIO pin {name} of {group} gives no valid C++ name ({label}); "
            f"the object is named {fallback}. Give the pin a name in SysConfig (GPIO > {group} "
            "> the pin > Name, for example PIN_LED1 for LED1) to choose it.",
            f"{syscfg.name}：{group} 的 GPIO 引脚 {name} 得不到合法的 C++ 名字（{label}）；对象"
            f"命名为 {fallback}。请在 SysConfig 中给引脚命名（GPIO > {group} > 该引脚 > Name，"
            "例如 PIN_LED1 得到 LED1）。",
        )
    )
    return fallback


def _gpio_physical(pin: dict, port_value: str, pin_value: str) -> str | None:
    """引脚的物理位置（PB8）：.syscfg 的 pin.$assign/$suggestSolution；没有时（TI 例程里的端口
    加引脚号写法，或求解器选的引脚）取自 SysConfig 输出的 PORT 和 PIN 宏的值（GPIOB、
    DL_GPIO_PIN_8）。都没有时为 None。
    The physical position of a pin (PB8): pin.$assign/$suggestSolution of the .syscfg; without
    it (the port plus pin number form of TI's examples, or a pin the solver chose) it comes from
    the values of the PORT and PIN macros of the SysConfig output (GPIOB, DL_GPIO_PIN_8). None
    when neither gives it.
    """
    if pin.get("pin"):
        return str(pin["pin"])
    port = re.search(r"\bGPIO([A-Z])\b", port_value)
    line = re.search(r"\bDL_GPIO_PIN_(\d+)\b", pin_value)
    if port and line:
        return f"P{port.group(1)}{int(line.group(1))}"
    return None


def _gpio_entries(
    syscfg: Path, instances: Instances, defines: dict[str, str], device_names: set[str]
) -> dict:
    """.syscfg 中 GPIO 组的引脚：标签（$name 去掉 PIN_ 前缀）-> 组、物理引脚、实际生成的宏和
    电气设置。跳过的引脚都给出警告；与器件宏同名的标签报错退出。
    The pins of the GPIO groups in the .syscfg: label (the $name without its PIN_ prefix) ->
    group, physical pin, the macros that were actually generated and the electrical settings.
    Every skipped pin is warned about; a label named like a device macro is an error.
    """
    entries: dict[str, dict] = {}
    for entry in instances.of_var.values():
        if entry["module"] != "GPIO" or not entry["name"]:
            continue
        group_name = entry["name"]
        # SysConfig 的宏以组名为前缀：组内所有引脚同端口时组级 PORT 宏（GPIO_KEYS_PORT），否则
        # 每个引脚自己的 PORT 宏（GPIO_LEDS_PIN_LED1_PORT）；PIN 和 IOMUX 宏总是每引脚一个。
        # The macros of SysConfig take the group name as their prefix: a group-level PORT macro
        # (GPIO_KEYS_PORT) when every pin of the group sits on the same port, else the PORT
        # macro of each pin (GPIO_LEDS_PIN_LED1_PORT); the PIN and IOMUX macros are always
        # per-pin.
        group_port = f"{group_name}_PORT" in defines
        for index in sorted(entry["gpio"]):
            pin = entry["gpio"][index]
            name = pin.get("name")
            if not name:
                logging.warning(
                    tr(
                        f"{syscfg.name}: pin {index} of the GPIO group {group_name} has no "
                        "name; it is skipped",
                        f"{syscfg.name}：GPIO 组 {group_name} 的第 {index} 个引脚没有名字；跳过",
                    )
                )
                continue
            port_macro = f"{group_name}_PORT" if group_port else f"{group_name}_{name}_PORT"
            pin_macro = f"{group_name}_{name}_PIN"
            iomux_macro = f"{group_name}_{name}_IOMUX"
            missing = [
                macro for macro in (port_macro, pin_macro, iomux_macro) if macro not in defines
            ]
            if missing:
                logging.warning(
                    tr(
                        f"{syscfg.name}: {', '.join(missing)} missing from the SysConfig output; "
                        f"the GPIO {name} is skipped",
                        f"{syscfg.name}：SysConfig 输出里没有 {', '.join(missing)}；"
                        f"跳过 GPIO {name}",
                    )
                )
                continue
            physical = _gpio_physical(pin, defines[port_macro], defines[pin_macro])
            if physical is None:
                logging.warning(
                    tr(
                        f"{syscfg.name}: cannot tell the pin of the GPIO {name} from "
                        f"{port_macro} and {pin_macro}; it is skipped",
                        f"{syscfg.name}：无法从 {port_macro} 和 {pin_macro} 得知 GPIO {name} "
                        "的引脚；跳过",
                    )
                )
                continue
            record = {
                "Group": group_name,
                "Pin": physical,
                "Port": port_macro,
                "PinMacro": pin_macro,
                "IOMUX": iomux_macro,
                "Direction": pin.get("direction", "OUTPUT"),
                "Resistor": pin.get("internalResistor", "NONE"),
            }
            if pin.get("interruptEn"):
                # SysConfig 的触发极性默认是 DISABLE（GPIOPin.syscfg.js）。
                # The trigger polarity of SysConfig defaults to DISABLE (GPIOPin.syscfg.js).
                record["Interrupt"] = pin.get("polarity", "DISABLE")
            label = _gpio_label(syscfg, group_name, name)
            if label in device_names or label in CPP_KEYWORDS:
                _fail(
                    tr(
                        f"{syscfg.name}: the GPIO object name {label} (pin {name} of "
                        f"{group_name}) is a C++ keyword or a macro of the device or of the "
                        "SysConfig output; rename the pin in SysConfig",
                        f"{syscfg.name}：GPIO 对象名 {label}（{group_name} 的引脚 {name}）是 "
                        "C++ 关键字，或器件、SysConfig 输出中的宏；请在 SysConfig 中给引脚改名",
                    )
                )
            if label in entries:
                logging.warning(
                    tr(
                        f"{syscfg.name}: two GPIO pins are named {label}; the later one wins",
                        f"{syscfg.name}：两个 GPIO 引脚都叫 {label}；以后一个为准",
                    )
                )
            entries[label] = record
    return entries


def _header_dma_channel(name: str, direction: str, defines: dict[str, str]) -> str | None:
    """SysConfig 输出里实例 name 在 direction（TX/RX）方向的 DMA 通道名：每个
    <name>_INST_DMA_TRIGGER_n 前面紧挨着它的通道的 <通道>_CHAN_ID。没有时为 None。
    The DMA channel name of the instance name in direction (TX/RX) in the SysConfig output:
    every <name>_INST_DMA_TRIGGER_n directly follows the <channel>_CHAN_ID of its channel. None
    when there is none.
    """
    channel = None
    for macro, value in defines.items():
        if macro.endswith("_CHAN_ID"):
            channel = macro[: -len("_CHAN_ID")]
        elif re.fullmatch(rf"{re.escape(name)}_INST_DMA_TRIGGER_\d+", macro):
            trigger = DMA_TRIGGER.fullmatch(value)
            if trigger and trigger.group(1) == direction and channel:
                return channel
    return None


def _dma_channel(name: str, entry: dict, direction: str, defines: dict[str, str]) -> str | None:
    """实例的 DMA 通道名：UART 是 DMA_CHANNEL_TX/RX，SPI 是事件通道，按触发方向区分（RX 的触发
    包括 RX_TIMEOUT）；.syscfg 没写通道名时取自 SysConfig 输出。
    The DMA channel name of an instance: DMA_CHANNEL_TX/RX for a UART, the event channels of an
    SPI told apart by their trigger direction (an RX trigger includes RX_TIMEOUT); when the
    .syscfg does not name the channel it comes from the SysConfig output.
    """
    channel = entry["dma"].get(f".DMA_CHANNEL_{direction}.$name")
    if channel:
        return channel
    for event in (1, 2):
        channel = entry["dma"].get(f".DMA_CHANNEL_EVENT{event}.$name")
        trigger = str(entry["params"].get(f"enabledDMAEvent{event}Triggers") or "")
        if channel and trigger:
            if direction == "RX" and re.search(r"_RX(_TIMEOUT)?$", trigger):
                return channel
            if direction == "TX" and trigger.endswith("_TX"):
                return channel
    return _header_dma_channel(name, direction, defines)


def _not_generated(syscfg: Path, module: str, name: str, entry: dict, defines: dict) -> str | None:
    """LibXR 驱动不支持的工作模式：I2C 只有目标模式（SysConfig 输出里没有 <name>_BUS_SPEED_HZ），
    SPI 是外设模式。返回原因的英文和中文，支持时为 None。
    A mode the LibXR driver does not support: an I2C in target mode only (no <name>_BUS_SPEED_HZ
    in the SysConfig output) and an SPI in peripheral mode. Returns the reason, or None when
    the mode is supported.
    """
    if module == "I2C" and f"{name}_BUS_SPEED_HZ" not in defines:
        return tr(
            f"{syscfg.name}: {name} is not in controller mode (no {name}_BUS_SPEED_HZ in the "
            "SysConfig output); the LibXR MSPM0 I2C driver is controller-only, so no object is "
            "generated and the instance is listed under Other",
            f"{syscfg.name}：{name} 不是控制器模式（SysConfig 输出里没有 {name}_BUS_SPEED_HZ）；"
            "LibXR 的 MSPM0 I2C 驱动只支持控制器，不生成对象，实例列在 Other 中",
        )
    if module == "SPI" and str(entry["params"].get("mode", "CONTROLLER")) != "CONTROLLER":
        return tr(
            f"{syscfg.name}: {name} is in {entry['params']['mode']} mode; the LibXR MSPM0 SPI "
            "driver is controller-only, so no object is generated and the instance is listed "
            "under Other",
            f"{syscfg.name}：{name} 是 {entry['params']['mode']} 模式；LibXR 的 MSPM0 SPI 驱动只"
            "支持控制器，不生成对象，实例列在 Other 中",
        )
    return None


def _pwm_channels(syscfg: Path, name: str, entry: dict, defines: dict[str, str]) -> list[int]:
    """PWM 实例的通道：SysConfig 输出里的 GPIO_<name>_C<n>_IDX；输出里没有时取 .syscfg 的
    ccp<n>Pin（$assign 或 $suggestSolution）。都没有时给出警告。
    The channels of a PWM instance: GPIO_<name>_C<n>_IDX in the SysConfig output; without them
    the ccp<n>Pin members of the .syscfg ($assign or $suggestSolution). A warning when neither
    gives any.
    """
    pattern = re.compile(rf"GPIO_{re.escape(name)}_C(\d+)_IDX")
    channels = sorted({int(m.group(1)) for macro in defines if (m := pattern.fullmatch(macro))})
    if not channels:
        channels = sorted(
            {int(m.group(1)) for member in entry["pins"] if (m := SYSCFG_PWM_CHANNEL.match(member))}
        )
    if not channels:
        logging.warning(
            tr(
                f"{syscfg.name}: the PWM {name} has no channel (no GPIO_{name}_C<n>_IDX in the "
                "SysConfig output and no ccp<n>Pin in the .syscfg); no PWM object is generated",
                f"{syscfg.name}：PWM {name} 没有通道（SysConfig 输出里没有 GPIO_{name}_C<n>_IDX，"
                ".syscfg 里也没有 ccp<n>Pin）；不生成 PWM 对象",
            )
        )
    return channels


def _syscfg_of(directory: str) -> Path:
    """directory 根目录唯一的 .syscfg；不是正好一个时报错退出。
    The single .syscfg in the root of directory; an error exits when there is not exactly one.
    """
    syscfgs = sorted(Path(directory).glob("*.syscfg"))
    if len(syscfgs) != 1:
        names = ", ".join(path.name for path in syscfgs) or tr("none found", "没有找到")
        _fail(
            tr(
                f"{directory} must hold exactly one .syscfg file in its root ({names})",
                f"{directory} 的根目录必须有且只有一个 .syscfg 文件（{names}）",
            )
        )
    return syscfgs[0]


def _device_of(syscfg: Path) -> tuple[str, dict[str, int]]:
    """.syscfg 的器件（@v2CliArgs 的 --device，或 --board 的板子表）和器件族的外设电源域；没有
    器件或器件未知时报错退出。
    The device of the .syscfg (--device of @v2CliArgs, or the board table for --board) and the
    peripheral power domains of its family; a missing or unknown device is an error.
    """
    meta = pin_project.read_syscfg(syscfg)
    board = pin_project.load_boards().get(meta.board or "")
    device = meta.device or (board or {}).get("device")
    if device is None:
        _fail(
            tr(
                f"{syscfg.name} does not name a device (@v2CliArgs --device or --board)",
                f"{syscfg.name} 没有给出器件（@v2CliArgs 的 --device 或 --board）",
            )
        )
    try:
        return device, _power_domains(device)
    except ValueError as error:
        _fail(tr(f"{syscfg.name}: {error}", f"{syscfg.name}：{error}"))


def parse_project(directory: str, output: str | None = None, summary: bool = True) -> None:
    """解析 directory 根目录的 .syscfg 工程并写出 YAML；summary 为真时打印摘要。
    Parse the .syscfg project in the root of directory and write the YAML; print a summary when
    summary is set.

    输出路径默认为该目录下的 .config.yaml。调用方（libxr parse）已确认目录存在且根目录含有一个
    .syscfg 文件。
    The output defaults to .config.yaml in that directory. The caller, libxr parse, has checked
    that the directory exists and the root holds one .syscfg file.
    """
    root = Path(directory)
    syscfg = _syscfg_of(directory)
    logging.info(tr(f"Processing {syscfg.name}...", f"正在处理 {syscfg.name}……"))
    device, power_domains = _device_of(syscfg)
    header, source = _sysconfig_output(root, syscfg)
    defines = _header_defines(header)

    instances = Instances(syscfg.read_text(encoding="utf-8", errors="replace"))
    peripherals: dict[str, dict] = {}
    other: dict[str, dict] = {}
    for module, section in GENERATED_MODULES.items():
        for name, entry in instances.peripherals(module).items():
            # .syscfg 没写外设时（求解器选的）取 SysConfig 输出的 <name>_INST。
            # When the .syscfg names no peripheral (the solver chose it) it comes from the
            # <name>_INST of the SysConfig output.
            peripheral = entry["peripheral"] or defines.get(f"{name}_INST") or None
            reason = _not_generated(syscfg, module, name, entry, defines)
            if reason:
                logging.warning(reason)
                other[name] = {"Module": module, "Peripheral": peripheral}
                continue
            record = {"Peripheral": peripheral}
            for direction in ("TX", "RX"):
                channel = _dma_channel(name, entry, direction, defines)
                if channel:
                    record[f"DMA_{direction}"] = channel
            if entry["pins"]:
                record["Pins"] = dict(entry["pins"])
            if module == "PWM":
                record["Channels"] = _pwm_channels(syscfg, name, entry, defines)
            peripherals.setdefault(section, {})[name] = record

    for entry in instances.of_var.values():
        module, name, peripheral = entry["module"], entry["name"], entry["peripheral"]
        if module in GENERATED_MODULES or module == "GPIO":
            continue
        if peripheral is None or peripheral.startswith("DMA_CH") or peripheral == "DEBUGSS":
            continue
        other[name or peripheral] = {"Module": module, "Peripheral": peripheral}

    # 每个外设实例所在的电源域（P1 的数据），gen 的时钟计算（M5）要用。
    # The power domain of every peripheral instance (the P1 data), for the clock computation of
    # gen (M5).
    clocks = _clock_configs(source)
    for _section, records in peripherals.items():
        for name, record in records.items():
            domain = power_domains.get(str(record["Peripheral"]))
            if domain is not None:
                record["PowerDomain"] = domain
            clock = clocks.get(name)
            if clock and not _clock_is_default(clock):
                record["SysConfigClock"] = clock

    data = {
        "Platform": "mspm0",
        "Syscfg": syscfg.name,
        "Mcu": {"Family": "MSPM0", "Type": device},
        "CPUCLK": _cpuclk(defines),
        "ULPCLKDivider": _ulpclk_divider(source),
        "GPIO": _gpio_entries(syscfg, instances, defines, _device_names(power_domains, defines)),
        "Peripherals": {**peripherals, "Other": other} if other else peripherals,
    }

    output_path = output or os.path.join(directory, ".config.yaml")
    if not data["Peripherals"] and not data["GPIO"]:
        logging.warning(
            tr(
                f"{syscfg.name} configures no peripheral or GPIO pin",
                f"{syscfg.name} 没有配置任何外设或 GPIO 引脚",
            )
        )
    if not _save_to_yaml(data, str(output_path)):
        sys.exit(1)
    if summary:
        _print_summary(data)


def _power_domains(device: str) -> dict[str, int]:
    """器件所属家族的外设电源域（P1 的 mspm0 数据：模块名 -> 0/1）；器件未知时抛出 ValueError。
    The peripheral power domains of the family of the device (the P1 mspm0 data: module ->
    0/1); an unknown device raises ValueError.
    """
    data = pin_layout.load_data("mspm0")
    _, family, _ = pin_layout.mspm0_family(device, data)
    return family.get("power_domains", {})
