"""libxr parse 对 MSPM0 工程：解析 SysConfig 工程并写出工程 YAML。
libxr parse for an MSPM0 project: parse the SysConfig project and write the project YAML.

工程是根目录中唯一的 .syscfg。解析读两个来源：.syscfg 本身（外设实例、参数和引脚分配），以及
SysConfig 生成的 ti_msp_dl_config.h/.c（实际生成的宏名、CPUCLK_FREQ 和 ULPCLK 分频）。工程目录
的 build* 里比 .syscfg 新的生成结果直接复用；否则用 SYSCONFIG_TOOL 运行一次（MSPM0_SDK_INSTALL_DIR
和 SYSCONFIG_TOOL，与 CMake 的 MSPM0SysConfig.cmake 用的环境变量相同），生成到临时目录。
The project is the single .syscfg in the root. Parsing reads two sources: the .syscfg itself
(peripheral instances, parameters and pin assignments) and the ti_msp_dl_config.h/.c that
SysConfig generates (the macro names actually emitted, CPUCLK_FREQ and the ULPCLK divider). A
generated output newer than the .syscfg under a build* directory of the project is reused;
otherwise SysConfig runs once (MSPM0_SDK_INSTALL_DIR and SYSCONFIG_TOOL, the environment
variables the CMake MSPM0SysConfig.cmake uses as well) into a temporary directory.

外设分两类：LibXR 有驱动的（UART、I2C、SPI、PWM）进入 Peripherals，gen 为它们生成对象；其余
（ADC12、DAC12、MCAN、QEI……）记入 Other，只作展示。GPIO 引脚进入 GPIO 段。
Peripherals split in two: the ones LibXR has drivers for (UART, I2C, SPI, PWM) go into
Peripherals and gen generates objects for them; the rest (ADC12, DAC12, MCAN, QEI, ...) are
recorded under Other for display only. The GPIO pins go into the GPIO section.
"""

from __future__ import annotations

import logging
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml
from xr_syntax.i18n import tr

from libxr import pin_layout, pin_project


def _save_to_yaml(data: dict, output_path: str) -> bool:
    """把工程数据写成 YAML，首行为 SysConfig 工程的生成文件说明；成功时为 True。
    Write the project data as YAML with a generated-file notice for a SysConfig project on the
    first line; True on success.
    """
    try:
        directory = os.path.dirname(output_path)
        if directory:
            os.makedirs(directory, exist_ok=True)
        with open(output_path, "w", encoding="utf-8", newline="\n") as file:
            file.write(
                "# Generated by `libxr parse` from the SysConfig project file; "
                "do not edit by hand.\n"
            )
            yaml.dump(
                data, file, allow_unicode=True, sort_keys=False, default_flow_style=False, indent=2
            )
        logging.info(
            tr(f"Configuration exported to: {output_path}", f"配置已导出到：{output_path}")
        )
        return True
    except (OSError, yaml.YAMLError) as error:
        logging.error(tr(f"YAML export failed: {str(error)}", f"YAML 导出失败：{str(error)}"))
        return False


def _print_summary(data: dict) -> None:
    """向标准输出打印配置摘要：器件、GPIO 引脚和各类外设实例。
    Print a configuration summary to standard output: the device, the GPIO pins and the
    peripheral instances of each kind.
    """
    print(tr("\n===== [Configuration Summary] =====", "\n===== [配置摘要] ====="))
    mcu = data.get("Mcu", {})
    print(
        tr(
            f"\nMCU: {mcu.get('Family', '')} {mcu.get('Type', '')}",
            f"\nMCU：{mcu.get('Family', '')} {mcu.get('Type', '')}",
        )
    )
    gpio = data.get("GPIO", {})
    print(tr(f"\nGPIO ({len(gpio)} pins):", f"\nGPIO（{len(gpio)} 个引脚）："))
    for label, pin in gpio.items():
        interrupt = f", {pin['Interrupt']} interrupt" if "Interrupt" in pin else ""
        print(f"  {label}: {pin['Pin']}, {pin['Direction']}{interrupt}")
    print(tr("\nActive Peripherals:", "\n已启用的外设："))
    for section, group in data.get("Peripherals", {}).items():
        print(tr(f"  {section}: {len(group)} instance(s)", f"  {section}：{len(group)} 个实例"))
        for name in group:
            print(f"    {name}")


# SysConfig 运行的时限（秒）。
# Time limit in seconds for a SysConfig run.
SYSCONFIG_TIMEOUT = 300

# LibXR 有驱动、gen 生成对象的模块：模块名 -> Peripherals 段的键。
# The modules LibXR has drivers for and gen generates objects for: module -> the key of the
# Peripherals section.
GENERATED_MODULES = {"UART": "UART", "I2C": "I2C", "SPI": "SPI", "PWM": "PWM"}

# 驱动会重设时钟配置的外设，SysConfig 写入的 clockSel 和 divideRatio 只起信息作用。
# Peripherals whose clock configuration the driver resets; the clockSel and divideRatio
# SysConfig wrote are informational only.
DRIVER_RESET_CLOCKS = ("I2C",)

SYSCFG_GPIO_PARAM = re.compile(r"^\.associatedPins\[(\d+)\]\.(\w+)$")
SYSCFG_PERIPH_MEMBER = re.compile(r"^\.peripheral\.(\w+)\.\$assign$")
SYSCFG_PWM_CHANNEL = re.compile(r"^\.peripheral\.ccp(\d+)Pin\.\$assign$")


def _strip_comments(text: str) -> str:
    """.syscfg 的正文：去掉块注释和行注释。
    The body of a .syscfg: block comments and line comments removed.
    """
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"^[ \t]*//.*$", "", text, flags=re.M)


class Instances:
    """一个 .syscfg 的全部实例：变量 -> 模块、名字、外设、参数、引脚成员和 DMA 子实例。
    Every instance of one .syscfg: variable -> module, name, peripheral, parameters, pin
    members and DMA sub-instances.
    """

    def __init__(self, text: str) -> None:
        """解析 .syscfg 的脚本正文，按变量记下每个实例的全部赋值。
        Parse the script body of a .syscfg and record every assignment of each instance by its
        variable.
        """
        text = _strip_comments(text)
        modules = dict(pin_project.SYSCFG_MODULE.findall(text))
        instances = dict(modules)
        instances.update(
            {
                var: modules[module]
                for var, module in pin_project.SYSCFG_INSTANCE.findall(text)
                if module in modules
            }
        )
        self.of_var: dict[str, dict] = {}
        for var, tail, value in pin_project.SYSCFG_ASSIGNMENT.findall(text):
            if var not in instances:
                continue
            entry = self.of_var.setdefault(
                var,
                {
                    "module": instances[var],
                    "name": None,
                    "peripheral": None,
                    "params": {},
                    "pins": {},
                    "dma": {},
                    "gpio": {},
                },
            )
            value = pin_project.syscfg_value(value)
            if tail == ".$name":
                entry["name"] = value
            elif tail == ".peripheral.$assign":
                entry["peripheral"] = value
            elif tail == ".peripheral.$suggestSolution":
                entry["peripheral"] = entry["peripheral"] or value
            elif tail.startswith(".peripheral."):
                member = SYSCFG_PERIPH_MEMBER.match(tail)
                if member:
                    entry["pins"][member.group(1)] = value
            elif tail.startswith(".DMA_CHANNEL_"):
                entry["dma"][tail] = value
            elif tail.startswith(".associatedPins["):
                index = int(re.match(r"^\.associatedPins\[(\d+)\]", tail).group(1))
                pin = entry["gpio"].setdefault(index, {})
                if tail == f".associatedPins[{index}].$name":
                    pin["name"] = value
                elif tail in (
                    f".associatedPins[{index}].pin.$assign",
                    f".associatedPins[{index}].pin.$suggestSolution",
                ):
                    # $assign 优先于 $suggestSolution；后写的 $suggestSolution 不覆盖 $assign。
                    # $assign wins over $suggestSolution; a later $suggestSolution does not
                    # override an $assign.
                    if tail.endswith(".$assign") or "pin" not in pin:
                        pin["pin"] = value
                else:
                    param = SYSCFG_GPIO_PARAM.match(tail)
                    if param and not param.group(2).startswith("$"):
                        pin[param.group(2)] = value
            elif "$" not in tail:
                entry["params"][tail.lstrip(".")] = value

    def peripherals(self, module: str) -> dict[str, dict]:
        """模块 module 的实例，按 .syscfg 中的出现顺序，实例名 -> 数据；没有名字的实例跳过。
        The instances of module, in .syscfg order, instance name -> its data; an instance
        without a name is skipped.
        """
        found = {}
        for entry in self.of_var.values():
            if entry["module"] == module and entry["name"]:
                found[entry["name"]] = entry
        return found


def _sysconfig_output(directory: Path, syscfg: Path) -> tuple[str, str]:
    """SysConfig 生成的 ti_msp_dl_config.h 和 .c 的内容：优先复用 build* 中比 .syscfg 新的输出，
    否则运行 SysConfig 到临时目录（用后删除）。
    The contents of the ti_msp_dl_config.h/.c SysConfig generates: an output under build* that
    is newer than the .syscfg is reused; otherwise SysConfig runs into a temporary directory
    (removed afterwards).
    """
    syscfg_mtime = syscfg.stat().st_mtime
    reused = sorted(
        (
            path
            for path in directory.glob("build*/**/syscfg/ti_msp_dl_config.h")
            if path.stat().st_mtime >= syscfg_mtime
        ),
        key=lambda path: path.stat().st_mtime,
    )
    if reused:
        header = reused[-1]
        source = header.with_name("ti_msp_dl_config.c")
        if source.is_file():
            build_dir = header.parent.parent
            label = (
                build_dir.relative_to(directory)
                if build_dir.is_relative_to(directory)
                else build_dir
            )
            logging.info(
                tr(
                    f"Reusing the SysConfig output in {label}",
                    f"复用 {label} 中的 SysConfig 输出",
                )
            )
            return header.read_text(encoding="utf-8", errors="replace"), source.read_text(
                encoding="utf-8", errors="replace"
            )

    tool = os.environ.get("SYSCONFIG_TOOL", "")
    sdk = os.environ.get("MSPM0_SDK_INSTALL_DIR", "")
    if not tool or not sdk or not os.path.exists(os.path.join(sdk, ".metadata", "product.json")):
        logging.error(
            tr(
                f"{directory}: no SysConfig output newer than {syscfg.name} found under build*, "
                "and SYSCONFIG_TOOL or MSPM0_SDK_INSTALL_DIR is not set (the environment "
                "variables the CMake build uses). Build the project once, or set them and run "
                "`libxr parse` again.",
                f"{directory}：build* 下没有比 {syscfg.name} 新的 SysConfig 输出，且没有设置 "
                "SYSCONFIG_TOOL 或 MSPM0_SDK_INSTALL_DIR（CMake 构建使用的环境变量）。"
                "请先构建一次工程，或设置它们后重新运行 `libxr parse`。",
            )
        )
        sys.exit(1)

    output = tempfile.mkdtemp(prefix="libxr-sysconfig-")
    try:
        command = [
            tool,
            "--compiler",
            "gcc",
            "--product",
            os.path.join(sdk, ".metadata", "product.json"),
            "--output",
            output,
            str(syscfg),
        ]
        result = subprocess.run(command, capture_output=True, text=True, timeout=SYSCONFIG_TIMEOUT)
        if result.returncode != 0:
            logging.error(
                tr(
                    f"SysConfig failed on {syscfg}:\n{result.stdout}{result.stderr}",
                    f"SysConfig 在 {syscfg} 上运行失败：\n{result.stdout}{result.stderr}",
                )
            )
            sys.exit(1)
        header = Path(output) / "ti_msp_dl_config.h"
        source = Path(output) / "ti_msp_dl_config.c"
        return header.read_text(encoding="utf-8", errors="replace"), source.read_text(
            encoding="utf-8", errors="replace"
        )
    finally:
        shutil.rmtree(output, ignore_errors=True)


def _defines(header: str) -> set[str]:
    """ti_msp_dl_config.h 定义的宏名。
    The macro names ti_msp_dl_config.h defines.
    """
    return set(re.findall(r"^#define\s+(\w+)", header, re.M))


def _cpuclk(header: str) -> int | None:
    """ti_msp_dl_config.h 里的 CPUCLK_FREQ；没有时为 None。
    The CPUCLK_FREQ of ti_msp_dl_config.h; None when it does not define one.
    """
    match = re.search(r"^#define\s+CPUCLK_FREQ\s+(\d+)", header, re.M)
    return int(match.group(1)) if match else None


def _ulpclk_divider(source: str) -> int:
    """ti_msp_dl_config.c 里 DL_SYSCTL_setULPCLKDivider 的分频数；没有调用时为 1。
    The divider of DL_SYSCTL_setULPCLKDivider in ti_msp_dl_config.c; 1 without a call.
    """
    match = re.search(r"DL_SYSCTL_setULPCLKDivider\s*\(\s*DL_SYSCTL_ULPCLK_DIV_(\d+)", source)
    return int(match.group(1)) if match else 1


def _clock_configs(source: str) -> dict[str, dict]:
    """ti_msp_dl_config.c 里每个实例的时钟配置：实例名（I2C_0）-> clockSel 和 divideRatio。
    The clock configuration of every instance in ti_msp_dl_config.c: instance name (I2C_0) ->
    its clockSel and divideRatio.
    """
    found: dict[str, dict] = {}
    for name, body in re.findall(r"static const \w+ g(\w+)ClockConfig = \{(.*?)\};", source, re.S):
        sel = re.search(r"\.clockSel = (\w+)", body)
        div = re.search(r"\.divideRatio = (\w+)", body)
        found[name] = {
            "clockSel": sel.group(1) if sel else None,
            "divideRatio": div.group(1) if div else None,
        }
    return found


def _clock_is_default(clock: dict) -> bool:
    """实例的 SysConfig 时钟配置是否为默认的 BUSCLK + 分频 1（驱动会重设的外设除外，那只影响
    SysConfig 写下的初值）。
    Whether the SysConfig clock configuration of the instance is the default BUSCLK with divider
    1; for a peripheral whose driver resets the clock this only describes the initial value
    SysConfig wrote.
    """
    sel, div = clock.get("clockSel"), clock.get("divideRatio")
    return sel in (
        None,
        "DL_I2C_CLOCK_BUSCLK",
        "DL_SPI_CLOCK_BUSCLK",
        "DL_TIMER_CLOCK_BUSCLK",
        "DL_UART_MAIN_CLOCK_BUSCLK",
    ) and div in (
        None,
        "DL_I2C_CLOCK_DIVIDE_1",
        "DL_SPI_CLOCK_DIVIDE_RATIO_1",
        "DL_TIMER_CLOCK_DIVIDE_1",
        "DL_UART_MAIN_CLOCK_DIVIDE_RATIO_1",
    )


def _gpio_entries(syscfg: Path, instances: Instances, defines: set[str]) -> dict:
    """.syscfg 中 GPIO 组的引脚：标签（$name 去掉 PIN_ 前缀）-> 组、物理引脚、实际生成的宏和
    电气设置。
    The pins of the GPIO groups in the .syscfg: label (the $name without its PIN_ prefix) ->
    group, physical pin, the macros that were actually generated and the electrical settings.
    """
    entries: dict[str, dict] = {}
    for entry in instances.of_var.values():
        if entry["module"] != "GPIO" or not entry["name"]:
            continue
        group_name = entry["name"]
        # SysConfig 的宏以组名为前缀：组内所有引脚同端口时组级 PORT 宏（GPIO_KEYS_PORT），否则
        # 每个引脚自己的 PORT 宏（GPIO_LEDS_PIN_LED1_PORT）；PIN 和 IOMUX 宏总是每引脚一个。
        # The macros of SysConfig take the group name as their prefix: a group-level PORT macro
        # (GPIO_KEYS_PORT) when every pin of the group sits on the same port, else the PORT
        # macro of each pin (GPIO_LEDS_PIN_LED1_PORT); the PIN and IOMUX macros are always
        # per-pin.
        group_port = f"{group_name}_PORT" in defines
        for index in sorted(entry["gpio"]):
            pin = entry["gpio"][index]
            name, physical = pin.get("name"), pin.get("pin")
            if not name or not physical:
                continue
            port_macro = f"{group_name}_PORT" if group_port else f"{group_name}_{name}_PORT"
            pin_macro = f"{group_name}_{name}_PIN"
            iomux_macro = f"{group_name}_{name}_IOMUX"
            missing = [
                macro for macro in (port_macro, pin_macro, iomux_macro) if macro not in defines
            ]
            if missing:
                logging.warning(
                    tr(
                        f"{syscfg.name}: {', '.join(missing)} missing from the SysConfig output; "
                        f"the GPIO {name} is skipped",
                        f"{syscfg.name}：SysConfig 输出里没有 {', '.join(missing)}；"
                        f"跳过 GPIO {name}",
                    )
                )
                continue
            record = {
                "Group": group_name,
                "Pin": physical,
                "Port": port_macro,
                "PinMacro": pin_macro,
                "IOMUX": iomux_macro,
                "Direction": pin.get("direction", "OUTPUT"),
                "Resistor": pin.get("internalResistor", "NONE"),
            }
            if pin.get("interruptEn"):
                record["Interrupt"] = pin.get("polarity", "RISE")
            label = name[4:] if name.startswith("PIN_") else name
            if label in entries:
                logging.warning(
                    tr(
                        f"{syscfg.name}: two GPIO pins are named {label}; the later one wins",
                        f"{syscfg.name}：两个 GPIO 引脚都叫 {label}；以后一个为准",
                    )
                )
            entries[label] = record
    return entries


def _dma_channel(entry: dict, direction: str) -> str | None:
    """实例的 DMA 通道名：UART 是 DMA_CHANNEL_TX/RX，SPI 是事件通道，按触发方向区分。
    The DMA channel name of an instance: DMA_CHANNEL_TX/RX for a UART, the event channels of an
    SPI told apart by their trigger direction.
    """
    name = entry["dma"].get(f".DMA_CHANNEL_{direction}.$name")
    if name:
        return name
    for event in (1, 2):
        channel = entry["dma"].get(f".DMA_CHANNEL_EVENT{event}.$name")
        trigger = entry["params"].get(f"enabledDMAEvent{event}Triggers")
        if channel and trigger:
            if direction == "RX" and trigger.endswith("_RX"):
                return channel
            if direction == "TX" and trigger.endswith("_TX"):
                return channel
    return None


def parse_project(directory: str, output: str | None = None, summary: bool = True) -> None:
    """解析 directory 根目录的 .syscfg 工程并写出 YAML；summary 为真时打印摘要。
    Parse the .syscfg project in the root of directory and write the YAML; print a summary when
    summary is set.

    输出路径默认为该目录下的 .config.yaml。调用方（libxr parse）已确认目录存在且根目录含有一个
    .syscfg 文件。
    The output defaults to .config.yaml in that directory. The caller, libxr parse, has checked
    that the directory exists and the root holds one .syscfg file.
    """
    root = Path(directory)
    syscfgs = sorted(root.glob("*.syscfg"))
    if len(syscfgs) != 1:
        names = ", ".join(path.name for path in syscfgs) or tr("none found", "没有找到")
        logging.error(
            tr(
                f"{directory} must hold exactly one .syscfg file in its root ({names})",
                f"{directory} 的根目录必须有且只有一个 .syscfg 文件（{names}）",
            )
        )
        sys.exit(1)
    syscfg = syscfgs[0]
    logging.info(tr(f"Processing {syscfg.name}...", f"正在处理 {syscfg.name}……"))

    header, source = _sysconfig_output(root, syscfg)
    meta = pin_project.read_syscfg(syscfg)
    board = pin_project.load_boards().get(meta.board or "")
    device = meta.device or (board or {}).get("device")
    if device is None:
        logging.error(
            tr(
                f"{syscfg.name} does not name a device (@v2CliArgs --device or --board)",
                f"{syscfg.name} 没有给出器件（@v2CliArgs 的 --device 或 --board）",
            )
        )
        sys.exit(1)

    instances = Instances(syscfg.read_text(encoding="utf-8", errors="replace"))
    peripherals: dict[str, dict] = {}
    for module, section in GENERATED_MODULES.items():
        for name, entry in instances.peripherals(module).items():
            record = {"Peripheral": entry["peripheral"]}
            for direction in ("TX", "RX"):
                channel = _dma_channel(entry, direction)
                if channel:
                    record[f"DMA_{direction}"] = channel
            pins = {member: pin for member, pin in entry["pins"].items()}
            if pins:
                record["Pins"] = pins
            if module == "PWM":
                channels = sorted(
                    int(match.group(1))
                    for member in entry["pins"]
                    if (match := SYSCFG_PWM_CHANNEL.match(f".peripheral.{member}.$assign"))
                )
                record["Channels"] = channels
            peripherals.setdefault(section, {})[name] = record

    other: dict[str, dict] = {}
    for entry in instances.of_var.values():
        module, name, peripheral = entry["module"], entry["name"], entry["peripheral"]
        if module in GENERATED_MODULES or module == "GPIO":
            continue
        if peripheral is None or peripheral.startswith("DMA_CH") or peripheral == "DEBUGSS":
            continue
        other[name or peripheral] = {"Module": module, "Peripheral": peripheral}

    # 每个外设实例所在的电源域（P1 的数据），gen 的时钟计算（M5）要用。
    # The power domain of every peripheral instance (the P1 data), for the clock computation of
    # gen (M5).
    power_domains = _power_domains(device)
    clocks = _clock_configs(source)
    for _section, records in peripherals.items():
        for name, record in records.items():
            domain = power_domains.get(str(record["Peripheral"]))
            if domain is not None:
                record["PowerDomain"] = domain
            clock = clocks.get(name)
            if clock and not _clock_is_default(clock):
                record["SysConfigClock"] = clock

    data = {
        "Platform": "mspm0",
        "Syscfg": syscfg.name,
        "Mcu": {"Family": "MSPM0", "Type": device},
        "CPUCLK": _cpuclk(header),
        "ULPCLKDivider": _ulpclk_divider(source),
        "GPIO": _gpio_entries(syscfg, instances, _defines(header)),
        "Peripherals": {**peripherals, "Other": other} if other else peripherals,
    }

    output_path = output or os.path.join(directory, ".config.yaml")
    if not data["Peripherals"] and not data["GPIO"]:
        logging.warning(
            tr(
                f"{syscfg.name} configures no peripheral or GPIO pin",
                f"{syscfg.name} 没有配置任何外设或 GPIO 引脚",
            )
        )
    if not _save_to_yaml(data, str(output_path)):
        sys.exit(1)
    if summary:
        _print_summary(data)


def _power_domains(device: str) -> dict[str, int]:
    """器件所属家族的外设电源域（P1 的 mspm0 数据：模块名 -> 0/1）。
    The peripheral power domains of the family of the device (the P1 mspm0 data: module -> 0/1).
    """
    data = pin_layout.load_data("mspm0")
    _, family, _ = pin_layout.mspm0_family(device, data)
    return family.get("power_domains", {})
