// Board bring-up of the HPM5301EVKLite BSP.
// init_bsp_pins() runs first so the console pins exist before the UART clock is
// enabled; it and the peripheral clock functions are generated by the HPM Pinmux
// Tool from boards/hpm5301evklite/tool_config.hpmpc. The LibXR objects for these
// peripherals are created in app_main().
#include "app_main.h"
#include "board.h"
#include "clock.h"
#include "pinmux.h"

int main(void)
{
  // Pins: UART0 PA00/PA01 (console), UART3 PB15/PB14, I2C3 PB13/PB12, SPI1 PA26-PA29,
  // GPTMR0 COMP1 PB08, ADC0 IN2 PB10, ACMP COMP1 PB09 / CMP1_INN4 PB11, LED PA10,
  // KEY&BOOT PA03, USB0 PA24/PA25 and PY00 (ID) / PY01 (OC)
  init_bsp_pins();

  // SDK board: PLL/clock tree, console on UART0, banner
  board_init();

  // Peripheral clocks
  init_uart3_clock();
  init_i2c3_clock();
  init_spi1_clock();
  init_gptmr0_clock();
  init_adc0_bus_clock();
  init_acmp0_clock();
  init_usb0_clock();

  app_main();
  return 0;
}
