// Generated by `libxr gen`; do not edit by hand.
// Generated from boards/hpm5301evklite/tool_config.hpmpc (HPM5301); the Pinmux Tool
// configures the pins via init_bsp_pins() in main.c and main.c stays BSP-owned. Put
// application code between the "User Code Begin" and "User Code End" markers.
#include "app_main.h"

#include "libxr.hpp"
#include "hpm_gpio.hpp"
#include "hpm_i2c.hpp"
#include "hpm_pwm.hpp"
#include "hpm_soc.h"
#include "hpm_timebase.hpp"
#include "xrobot_main.hpp"

using namespace LibXR;

/* User Code Begin 1 */
/* User Code End 1 */

extern "C" void app_main(void)
{
  /* User Code Begin 2 */
  /* User Code End 2 */

  // Timebase and platform
  static HPMTimebase timebase;
  PlatformInit();

  // GPIO: init_bsp_pins() configured pa10 (PA10) as an output pin, pa3 (PA03) as an input
  // pin with a pull-down. The interrupt edge comes from the pinmux and every object
  // carries its port IRQ; RegisterCallback and EnableInterrupt belong to the consumer (a
  // Module or the User Code).
  static HPMGPIO pa10(HPM_GPIO0, GPIO_DI_GPIOA, 10, IRQn_GPIO0_A);
  static HPMGPIO pa3(HPM_GPIO0, GPIO_DI_GPIOA, 3, IRQn_GPIO0_A);

  // I2C: blocking transfers; the DMA-backed background path runs on dma_mgr.
  static HPMI2C i2c3(HPM_I2C3, clock_i2c3, {100000U});

  // PWM on a GPTMR comparator: the SoC has no PWM peripheral, so HPMPWM takes its GPTMR
  // fallback path; the duty comparator is fixed at 0 and SetConfig is called when
  // libxr_config sets a frequency.
  static HPMPWM pwm_gptmr0_ch1(reinterpret_cast<LibXRHpmPwmType*>(HPM_GPTMR0),
                               clock_gptmr0, 1, 0, HPMPWM::Polarity::NORMAL);

  // Hardware registration
  XR_REGISTER(pa10, LibXR::GPIO);
  XR_REGISTER(pa3, LibXR::GPIO);

  XR_REGISTER(pwm_gptmr0_ch1, LibXR::PWM);

  XR_REGISTER(i2c3, LibXR::I2C);

  /* User Code Begin 3 */
  /* User Code End 3 */
  XROBOT_MAIN();
}
