// Generated by `libxr gen`; do not edit by hand.
// Generated from boards/rmcs_slave_lite/tool_config.hpmpc (HPM5361); the Pinmux Tool
// configures the pins via init_bsp_pins() in main.c and main.c stays BSP-owned. Put
// application code between the "User Code Begin" and "User Code End" markers.
#include "app_main.h"

#include "libxr.hpp"
#include "hpm_gpio.hpp"
#include "hpm_power.hpp"
#include "hpm_soc.h"
#include "hpm_timebase.hpp"
#include "xrobot_main.hpp"

using namespace LibXR;

/* User Code Begin 1 */
/* User Code End 1 */

extern "C" void app_main(void)
{
  /* User Code Begin 2 */
  /* User Code End 2 */

  // Timebase and platform
  static HPMTimebase timebase;
  PlatformInit();
  static HPMPowerManager power_manager;

  // GPIO: init_bsp_pins() configured pb11 (PB11) as an output pin, pb13 (PB13) as an
  // output pin, pb12 (PB12) as an input pin, pb10 (PB10) as an input pin, pa31 (PA31) as
  // an input pin with a pull-down. The interrupt edge comes from the pinmux and every
  // object carries its port IRQ; RegisterCallback and EnableInterrupt belong to the
  // consumer (a Module or the User Code).
  static HPMGPIO pb11(HPM_GPIO0, GPIO_DI_GPIOB, 11, IRQn_GPIO0_B);
  static HPMGPIO pb13(HPM_GPIO0, GPIO_DI_GPIOB, 13, IRQn_GPIO0_B);
  static HPMGPIO pb12(HPM_GPIO0, GPIO_DI_GPIOB, 12, IRQn_GPIO0_B);
  static HPMGPIO pb10(HPM_GPIO0, GPIO_DI_GPIOB, 10, IRQn_GPIO0_B);
  static HPMGPIO pa31(HPM_GPIO0, GPIO_DI_GPIOA, 31, IRQn_GPIO0_A);

  // Hardware registration
  XR_REGISTER(power_manager, LibXR::PowerManager);

  XR_REGISTER(pb11, LibXR::GPIO);
  XR_REGISTER(pb13, LibXR::GPIO);
  XR_REGISTER(pb12, LibXR::GPIO);
  XR_REGISTER(pb10, LibXR::GPIO);
  XR_REGISTER(pa31, LibXR::GPIO);

  /* User Code Begin 3 */
  /* User Code End 3 */
  XROBOT_MAIN();
}
